### ISSUE TITLE
[management] No invitation to redeploy after delete a keyless plan

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#1116]
### Steps to Reproduce (for bugs)

1. create an api with a published keyless plan
2. check that api respond
3. close the keyless plan
4. no "deploy" message is shown

### Your Environment

* Version used: 1.14

**Comment by brasseld** [comment]
This issue is due to the fact that when we are closing a key_less plan, we are simply deleting it.
Then, when we are checking the sync status, the plan does not exist anymore so we do not know that there was a previously deleted plan.
The solution would be to set the plan status to close instead of deleting it.
WDYT ?

**Comment by brasseld** [comment]
There is a PR https://github.com/gravitee-io/gravitee-management-webui/pull/593 if you want to have a try.

It means that, now, all plans are closed instead of being deleted. So `key_less` plans and plans without subscriptions are also closed.
