### ISSUE TITLE
[portal] add in the API list the project name

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#1187]
The project name is registered in metadata and the availability is based on last month health check metric

**Comment by GGui** [comment]
Manage the project name through the Metadatas.
The project name is display in the api list and the api detail

**Comment by NicolasGeraud** [comment]
hi @GGui 
a project name is specific to your company. So we don't want to put it in Gravitee.

You could easily add a default project name in general metadatas (and override it in each api) and add this metadata in the api header (feature available since v1.20).

This is why I want to close this issue and not accept your pull requests. Is it ok for you ?

**Comment by GGui** [comment]
You can close this issue
