### ISSUE TITLE
[repository] [mongodb] Add Support for MongoDB SRV Records

### ISSUE THREAD

**Issue by DaspawnW** [gravitee-io/issues#1208]
The [3.6 MongoDB Driver](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format) supports SRV Record DNS Lookup. This allows good integration into Consul Cluster (As you also support for Discovering endpoints)

### Expected Behavior
If I write a connection url in format mongodb+srv://server.example.com/ the MongoDB Driver should ask a DNS Server for a SRV Record to resolve connection information.

### Current Behavior
Not Working

### Possible Solution
Upgrade of the Mongo Version to 3.6 in the gravitee-repository-mongodb github project

**Comment by brasseld** [comment]
Ok, according to the compatibility matrice, upgrade to 3.6 may be done quite safely.
http://mongodb.github.io/mongo-java-driver/3.6/upgrading/#compatibility

Need to have a look to Spring Data support because latest version assert compatibility only for Mongo 3.4 : https://docs.spring.io/spring-data/mongodb/docs/1.10.11.RELEASE/reference/html/#new-features.1-10-0
