### ISSUE TITLE
API Manager shows endpoints as "/foo", without "https://gateway/" part

### ISSUE THREAD

**Issue by hfuru** [gravitee-io/issues#1633]
Clicking on API Gallery : api Foo shows "Endpoint: /foo" at top right instead of "Endpoint: https://gateway/foo"

### Expected Behavior

Include "scheme://host/" part in displayed endpoint

### Steps to Reproduce (for bugs)

1. Use the attached [constants.json.gz](https://github.com/gravitee-io/issues/files/2532731/constants.json.gz) - that's my prime suspect since Gravitee has been sensitive to stuff there before.
2. In the web portal, create a api Foo, path /foo, keyless plan, start it.
3. Go to API Gallery and then Foo, look at Endpoint at the top.

### Your Environment

* Version used: 1.20.1
* Browser Name and version: Firefox 63.0
* Operating System and version: Linux, RHEL 7.5

**Comment by brasseld** [comment]
Hi @hfuru,

Since Gravitee.io, we are slightly moving configuration from constants.json to the management-api.

This, was also applied to something we call "API Headers" where you can define what would be the headers you want to show in the API Gallery.

You can have a look to our demo instance at https://demo.gravitee.io/#!/management/settings/apiportalheader

Let me know if it helps you.

Regards,

**Comment by hfuru** [comment]
The demo says "Session expired, redirecting to home..." and after that it looks like the normal front page.
Tried first with firefox, then with fresh browser session with chromium-browser

**Comment by hfuru** [comment]
OK, setting api.endpoint to "https://apim-utv42.uio.no${api.proxy.contextPath}" worked.  Thanks.
Is/will there be a way to set that automatically when installing Gravitee?

**Comment by brasseld** [comment]
Hi @hfuru 

Starting from Gravitee.io 1.22, there is a new feature called "Entry-point" which is allowing you to define all the API endpoint as per their sharding tags.
