### ISSUE TITLE
[management-ui] No logs errors with status code 403

### ISSUE THREAD

**Issue by nsn0x01** [gravitee-io/issues#1678]
Hi,

I'm using last docker images and I have enabled the proxy logging and it is working well except for the requests with status code 403,  logs are empty, but I would like to able to see what  headers and API key i'm receiving.

**Comment by brasseld** [comment]
Hi @nsn0x01,

You can't see requests from logs because, as the API Key is invalid, we don't know that this one was associated to a plan / API.

**Comment by nsn0x01** [comment]
Hi @brasseld 

I guess we can lookup the associated plan by the endpoint called (if valid)

**Comment by brasseld** [comment]
Hi @nsn0x01 

Absolutely not, because endpoint may be called by multiple plans.

**Comment by nsn0x01** [comment]
Hi @brasseld 

yes that's true, but could we set as a generic log for this? Anyway in logs view, I see the error 403 but headers and body are not logged, so my initial was not totally correct, the error 403 seems to be logged without any details.

**Comment by brasseld** [comment]
As I told you previously, if the api-key can not be validated, we can't ensure that the request is relative to a given plan.

Thanks to the context-path, we still know which API you're calling so that's the reason why you can see the log in API's logs.

Now the body is not logged because we are not reading the body content of the request, until we did not validate the request (HEAD part).

Is that clear ?

**Comment by nsn0x01** [comment]
Yes it's clear, thank you very much for the info,
