### ISSUE TITLE
[management-api] Groups mapping for OAuth2 users are never refreshed

### ISSUE THREAD

**Issue by briankrug** [gravitee-io/issues#1698]
When a user logins into the Management REST API using OAuth2 for the first time they may be assigned a set of Groups based on the user info and the configured Group Mappings. However, on subsequent logins this set of Groups is never refreshed. This is a problem when the user info changes (such as if a user is granted certain permissions in the Authentication Provider).

### Expected Behavior
The set of Groups for a user should be adjusted each time a user logs in

### Possible Solution
Run through the Groups mapping exercise each time a user logs in

### Context
We use certain attributes in the user info to indicate user roles which we map to groups. The groups control which APIs are visible to the user.

### Your Environment
* Version used: 1.18.1

**Comment by vlemaitre** [comment]
The issue is the same for role mapping.
It would be good to have the possibility to configure when the group / role bindings are refreshed : 
- at each log in
- only at first log in

**Comment by stuartwakefield** [comment]
Hi, is there any plans in the near term to support this? We are looking at integrating Gravitee with our OpenID Connect IdP. It would be useful to have the role mappings refreshed upon login so that we don't have to update Gravitee separately when roles / access / permissions change for our users. :+1:
