### ISSUE TITLE
[gateway] Add extension point for more granular OAuth2 scope save/check

### ISSUE THREAD

**Issue by zdenda-online** [gravitee-io/issues#1849]
In order to be able to store more granular data about scope approval (consent)
as an API publisher
I need be able to extend/enhance current scope approval (ApprovalServiceImpl).

### Detailed Context
We want to use Gravitee.io AM for PSD2 context (open banking) and in (national) standards require that (bank) end user will be giving approval not only to scope (e.g. access bank accounts) but also adds more information/data (e.g. what specific accounts 3rd-party can access).

### Possible Solution
In current ApprovalService, allow some extension via 2+ interfaces that will allow further customization during:
* saveApproval (e.g. call some external service to store more information about approval/consent)
* checkApproval (e.g. call some external service to check more granular approval/consent).

**Comment by brasseld** [comment]
Hi @zdenda-online 

Your use-case is really interesting.

Do you think that there are here some opportunities to provide "dynamic" scopes.
For example, if you're looking for `read_account` scope, then the end-user is checking the accounts for which the consent is valid and we can suffix the read_account scope with the account's number.

So scope read_account_xxxxxxxxxxx will be stored in AM instead of `read_account`. 

WDYT ?

ping @tcompiegne

**Comment by zdenda-online** [comment]
Hi @brasseld,

that is a good idea but unfortunately, these won't work for us.
Mainly because scopes from "standards" (AISP, PISP, CISP) are fixed (must be in this form) as they are also part of further processings like client certificates and so on.

So that I only see a way of some extension point in `ApprovalService`. It could be some "different" interface inside or maybe it can be implemented as a decorator (a class implementing `ApprovalService` interface as well that will call "original" `ApprovalService` via its dependency).

**Comment by brasseld** [comment]
Ok so in that case, you must be able to store additional information to approval "entities"...

In that case, you're right, the extension point is a best idea.
