### ISSUE TITLE
[portal] API Gallery: css issue for the API logo

### ISSUE THREAD

**Issue by Parkchanjun** [gravitee-io/issues#2113]
![1](https://user-images.githubusercontent.com/18658449/55366361-5f253100-5523-11e9-8aee-5b2bb9b1abd8.PNG)

![2](https://user-images.githubusercontent.com/18658449/55366363-62202180-5523-11e9-8795-1370b78ed928.PNG)

<1> Photos of API introduction pop up to the side.
<2> The introduction of API Documentation is dimly visible.

**Comment by adubreuiltk** [comment]
I faced the same issue and the workaround is to provide a squared picture.

**Comment by brasseld** [comment]
@adubreuiltk perhaps you can propose a PR to implement this squared picture ?

**Comment by adubreuiltk** [comment]
> perhaps you can propose a PR to implement this squared picture ?

I'm not a CSS expert, but I fixed that issue by adding the following entry in my custom CSS file (ir in `graviteeio-management-ui-1.25.0/themes/assets/gravitee.css`):

```css
.gravitee-media img {
    width: 100%;
}
```

I am not sure if it is the best fix, but it works (that's why I did not propose a PR).

I also tried to vertically align the picture (displayed in a 80x80 square), but I was unable to find a solution.
