### ISSUE TITLE
[gateway] [dynamic-routing] API without endpoint configuration 

### ISSUE THREAD

**Issue by mknair75** [gravitee-io/issues#2245]
In a scenario where a custom end point is used that is not known at the time of API configuration, it will be convenient to use a blank end point configuration (currently there is a default end point and end point group discovery using consul) , then use a Dynamic routing policy to route the request to a custom URL derived during run time ( using a HTTP call out) . 

The capability we are looking for is to support blank end point defintion in API configuration and support the need to forward to a custom end point through dynamic routing (with ot without reference to the end point configuration)

**Comment by aelamrani** [comment]
And why not deleting all endpoints from your group?

**Comment by mknair75** [comment]
We tried creating an empty end point group. After that attached a dynamic routing policy. Got a service unavailable error.

**Comment by aelamrani** [comment]
OK so no, it's not possible to use the policy Dynamic Routing to call an undefined endpoint for many reasons.

**Comment by mknair75** [comment]
So only option is to create a custom service discovery module and use that ?

**Comment by brasseld** [comment]
Hi @mknair75 

When you're using the Dynamic Routing policy, we are trying to get a reference to endpoint if possible that's the reason why you need at least one endpoint.

The reason for this is that we need to configure the way to reach the backend. And because of this, we need an endpoint.

So you have to option in your case:
* Create a dummy endpoint, just to define the HTTP configuration (the one which will be used to invoke the backend after Dynamic Routing)
* Use service discovery (but I'm not sure you need it for your use-case).

**Comment by mknair75** [comment]
@brasseld . The first option works. Thanks !

**Comment by brasseld** [comment]
Ok cool !

May I close the issue ?

**Comment by aelamrani** [comment]
Why not rely on HTTP configuration of en empty group?
