### ISSUE TITLE
open source gateway plateform selection comparison

### ISSUE THREAD

**Issue by cmdares** [gravitee-io/issues#2327]
Open Source Gateway selection is currently under way.
Preliminary selection with gravitee-io and tyk.io
How about comparison of two platforms In order to more accurately analyze the time when their own platform building methods.
my backend app api use springcloud with swagger.
Assessment point:
1.Performance
2.Custom plug-in
4.Security policy
5.Monitor
6.Convenience
7. support both rest api and webpage proxy

**Comment by brasseld** [comment]
Hi @cmdares,

We do not compare our platform to our competitors and not providing benchmark comparison.

All the points you mentioned are addressed by Gravitee.
A difference with tyk is about the language since Gravitee.io is fully written in Java and custom extension must be develop in Java also where Tyk is developed in Go.
About the security, we are covering all the common security concerns: jwt, oauth, apikey. Please note that we are also providing our own authorization server fully OIDC compliant (and certified).

Gravitee has been built to cover all the enterprise needs, from the management to the deployment... no need to say that gravitee.io is the best OSS api management enterprise ready !

If you have more questions, please ask them using our gitter channel, it will be easier to discuss and share.

Cheers

**Comment by brasseld** [comment]
No feedback on this issues, I'm closing it.

Feel free to ask if you have more questions.

Regards,
