### ISSUE TITLE
[policy] [quota] Async Quota Limit Does Not Aggregate

### ISSUE THREAD

**Issue by briankrug** [gravitee-io/issues#2391]
When you set a Quota Limit to async, it does not aggregate its counts across all the nodes.

### Expected Behavior
Quotas are generally applied across the whole cluster and not at a per-node basis, so The QuotaPolicy should aggregate its counts across all nodes.

### Current Behavior
Whether the Quota count is aggregated or not is dependent on the async property of the Quota Policy Configuration, but these are really separate concerns.

### Possible Solution
In io.gravitee.policy.quota.QuotaPolicy, the createRateLimitKey method should not use the async parameter but always return a key string that does not depend on the node id.

### Steps to Reproduce (for bugs)
1. Set up a two node gateway
2. Establish an Quota Policy on an API Key with async=true
3. Hit each node round-robin
4. The Quota allows twice the number of requests as it should

### Your Environment
* Version used: 1.18.0

**Comment by brasseld** [comment]
The purpose of the async mode is to not rely on the underlying repository to store the counter.
In that way, the gateway is storing the counter locally before aggregating and updating it each X seconds (10 seconds by default).
That's the main drawback of the async mode and as you seen, the policy may allow twice the nimber of requests in certain circonstances.
I'm not sure this is an issue as it's the expected behavior.
If you want to rely on a whole cluster basis, you should not use the async mode.

In other words: async is not about the way to store the counter into the datastore but the way we are aggregating and updating the counter on a whole cluster basis.

Is it clearest for you?

Moreover, we are working on a new reactive implementation of the rate-limiting feature: this would enhance the way we are managing counters for both async and non-async mode, and make usage of a get-and-increment function instead of distinct function `get` then `save`. See https://github.com/gravitee-io/gravitee-policy-ratelimit/pull/26/files

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/2570
