### ISSUE TITLE
[APIM Management UI] No access to Documentation and HEALTH

### ISSUE THREAD

**Issue by julienfradillon** [gravitee-io/issues#2468]
Hello,
We want to give access to read-only APIs in production to certain people.
To do this, we created a role with only read rights.
The problem is that with these rights, the people concerned can not see the Proxy / Health-check tab nor the Portal / Pages tabs.

**Comment by julienfradillon** [comment]
![Ko_on_clic](https://user-images.githubusercontent.com/51477759/61302124-8a3b4400-a7e5-11e9-9f4a-8ca4ca3fded9.JPG)
![no_health_check](https://user-images.githubusercontent.com/51477759/61302125-8ad3da80-a7e5-11e9-9510-b7b4a2f02671.JPG)
![Role](https://user-images.githubusercontent.com/51477759/61302129-8ad3da80-a7e5-11e9-86c7-ce56d3f6380e.JPG)

**Comment by NicolasGeraud** [comment]
Hi,

for the documentation, you have access only to published pages. Because read access to the documentation is the basic permission used in the portal.
We know it's a limitation of our permission system (used in the management and the portal). We are working on a big update to fix this.

for the Healthcheck, it's a bug (only users with CREATE permission can see it). -> #2566

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/issues/issues/2566
