### ISSUE TITLE
[management] Password problem

### ISSUE THREAD

**Issue by PaloSanto5482** [gravitee-io/issues#2562]
### Expected Behavior
User should log in. 
Password should work

### Current Behavior
 After creating a user  and setting his password from an email link, password doesn't work. I have to reset it using Admin account, and then it works. 

### Your Environment

* Version used: 1.28.1
* Operating System and version: Windows 10 
* Gravitee runs on Docker Containers
* Gravitee with MongoDB

**Comment by brasseld** [comment]
Did you set any special character within the password ?

**Comment by PaloSanto5482** [comment]
No, but I set same password after reset and then it works.

**Comment by graviteeLover3000** [comment]
I encountered the same problem. It seems to happen randomly, because sometimes the set up password from an email link works and sometimes it doesn't and you have to reset it to work. I used really simple passwords (like qwerty) without any special characters, only letters. Gravitee was set up on Docker containers with MongoDB.

**Comment by brasseld** [comment]
Do you have multiple instances of the management-api ?

**Comment by PaloSanto5482** [comment]
No, only one instance

**Comment by aelamrani** [comment]
Seems to be the same issue as in https://github.com/gravitee-io/issues/issues/2299

**Comment by PaloSanto5482** [comment]
Idk, but when i don't provide a '+' sign everything usually works.  Sometimes the problem occurs and then I have to reset the password from Admin account

**Comment by aelamrani** [comment]
Do you have any stacktrace to share when it occurs?
