### ISSUE TITLE
[policy] [transform-headers] Pass user/pass to backend api 

### ISSUE THREAD

**Issue by ssoogur** [gravitee-io/issues#2670]
we have backend api which is protected with user/password . I wrapped this api with Gravitee api gateway and assigned oauth policy which works well , since backend api is protected with user/password how would I pass credential to backend api ?

**Comment by brasseld** [comment]
Which credentials would you like to pass to the backend ?
You're looking to set the same credentials (through basic auth?) for all the users ?

**Comment by ssoogur** [comment]
yep pass the same credential though basic auth for all users

**Comment by brasseld** [comment]
so in that case, from API > Design > Policies, you can add a `Transform Headers` policy and add a new header `Authorization: Basic base64(username: password)`

The other option is to set the header at the endpoint level:
<img width="629" alt="Capture d’écran 2019-09-24 à 12 14 23" src="https://user-images.githubusercontent.com/133094/65503348-0aa4b200-dec5-11e9-87e3-ad7dccbff562.png">

**Comment by ssoogur** [comment]
thanks a Lot that resolved the issue .

**Comment by ssoogur** [comment]
Thank you very much that resolved the issue

**Comment by mannharleen** [comment]
@brasseld 
How would we extend this if the backend api was actually using oauth as well ??

**Comment by brasseld** [comment]
Would the token be specific to a user ?

Basic authentication is something quite static so you can reuse the same credentials between multiple (all ?) the requests.
OAuth token is more dynamic because of its expiration time so that's definitely not something you can do by using static headers at endpoint level.

For that purpose, I would probably go by using HTTP Callout policy which would allow to generate an oauth token and pass it to the upstream.
