### ISSUE TITLE
[policy] [jwt] EL variable endpoint not resolved into JWKS URL

### ISSUE THREAD

**Issue by damodeo** [gravitee-io/issues#3257]
If I use the full URL into the JWKS resolver, the policy works, if I use EL to put a variable for endpoint doesn't work. In the Dynamic Routing Scenario, the variable of the endpoint with EL works well.

### Expected Behavior
The same behavior if I use plain URL or EL variable.

### Current Behavior
Log:
15:58:40.650 [vert.x-eventloop-thread-0] [] ERROR io.gravitee.policy.jwt.JWTPolicy - [request-id:9eb7265f-5421-430b-b726-5f5421230b19] [request-path:/myapp/fruit/2] no protocol: {#endpoints['Service_JWKS']}

### Possible Solution
N.A.

### Steps to Reproduce (for bugs)
1. Create Endpoint: Service_JWKS - http://127.0.0.1/service/jwks.json?client_id=7777777
2. Add Policy JSON Web Tokens with JWKS_URL: {#endpoints['Service_JWKS']}
3. Test your API (Error 401 not authorized)

### Context
Set all IPs into an endpoint variable to use it inside the Policies, central management.

### Your Environment
* Version used:  1.26.0 (build: 516) revision#795110cda43cdcb9664db784e413f3075e91f0ca
* Operating System and version: Centos 7.x

There is the same issue #2485 opened on 23 Jul 2019.

**Comment by brasseld** [comment]
Hi @damodeo 

IMHO, the resolution of the jwks url must not be based on `endpoints` because it means that you'll have to create the jwks endpoint for each API.

For the moment, I would say that the best, for your use-case, would be to define a dictionary and set the jwks url as part of this dictionary. It would make it easier to manage a single url shared across multiple APIs / plans. WDYT ?

But it does not resolve the fact that the jwks url can not be resolved using EL...
