### ISSUE TITLE
management-ui: Allow the user to create an APP from the subscribe Wizard

### ISSUE THREAD

**Issue by gustavovalverde** [gravitee-io/issues#3328]
When a user subscribe the first time, it might don't know that gravitee needs an application name

### Expected Behavior

Allow new users to create an application from the subscription steps:
![image](https://user-images.githubusercontent.com/16890942/76543402-d914a880-645c-11ea-9436-6aa1f5264721.png)

### Current Behavior

The user might don't know what to do in this screen if there are no available apps to select. 

### Possible Solution

Allow to create application instead of selecting one from the drop-down.

### Your Environment

* Version used: 1.30.5
* Browser Name and version: Edge 10
* Operating System and version: Windows 10

**Comment by brasseld** [comment]
Hey @gustavovalverde 

I got your point.

I want to let you know that we would not support this portal anymore since we are planning to provide a new one as part of the v3 release (for end of april).

You can see current version from https://v3.nightly.gravitee.io/

Please let me know if you have any question.

Regards,
