### ISSUE TITLE
Support of GraphQL

### ISSUE THREAD

**Issue by tko99** [gravitee-io/issues#3923]
REST API are really great but it becomes to be quite limiting once the business needs grow.
GraphQL is a highlt trending upgrade with killng features (REST-like API, pubsub model/async, introspection, business resource-oriented, simplification of API versioning, very few endpoints...).

However, there is a huge open point: how to manage authorization and permissions?

We don't want to expose out GraphQL server on internet, and we would like an API gateway in the middle to bring all its existing key features (auth, rate limiting, policies...)

### Context
We are moving from REST to GraphQL API for 2 reasons:
- our business needs evolves and it becomes hard to maintain all API whenever we need to add new attributes to some business objects (e.g. customer, book, author...)
- more reactive and async frontend applications

**Comment by brasseld** [comment]
Hi @adubreuiltk 

Do you have any pointer / reference that show what can be the gain offered by an API Gateway in the case of GraphQL. What kind of features it may provide, etc...

**Comment by t1** [comment]
Most API Gateway features for GraphQL services would be very similar to those for REST services: routing, caching, CORS, authentication, logging, etc. Some things just need very different ways of configuration, mostly because they can't be done simply per URL.

Take authorization: in a service for super heroes, you may want to limit read access to their current location to certain clients. In a RESTful service, the location would be modeled as a separate resource (URL), so access restrictions can be applied to this URL. In a GraphQL service, the location would directly be a field of the super hero object graph, so the service that resolves this field needs to know about the roles and grants of the client. After doing the authentication, the API Gateway will have to push this authorization information down into the service, maybe in a JWT token. I personally think this is a good pattern also for REST services.

Also Quotas and Rate-Limiting have to consider very different issues ([see](https://www.howtographql.com/advanced/4-security/)).

An API Gateway could also transform REST to GraphQL and vice versa.

**Comment by t1** [comment]
Maybe the [Apollo GraphQL](https://www.apollographql.com) is a good pointer for basic requirements.

**Comment by brasseld** [comment]
Thanks guys for your feedbacks.

We are looking to provide GraphQL support (mainly from a policy point of view) by adding the ability to define and configure policies not only for a given path / methods, but also for a given resource path in the object graph.

This will fit well with something we are working on, called "policy design studio" which is providing a completely new way to define policies.

That way, you'll be able to complete your GraphQL use-cases.

WDYT?

**Comment by t1** [comment]
That sounds very interesting! Can you tell us some more details?

**Comment by adubreuiltk** [comment]
>(...) but also for a given resource path in the object graph.

That's exactly what we are looking for !!!!!

GraphQL requires a new approach to manage permissions and policies. Endpoints cannot be the main driver for RBAC.

**Comment by brasseld** [comment]
So that's something we are considering and which already part of the roadmap.
But going deeper on it, we must have to work on the new Policy Design Studio which will help us to define policies not only for a given path / method, but also for some other request properties / payload content, definition content.

**Comment by ca-simone-chiorazzo** [comment]
Is there any plan to put the GraphQL support in the roadmap?

**Comment by mouligno** [comment]
hi @ca-simone-chiorazzo there is plan to support GraphQL as you can view here : https://dev.gravitee.io/feedback-portal

**Comment by ca-simone-chiorazzo** [comment]
@mouligno Thanks a lot for the quick response. Looking at https://portal.productboard.com/gravitee/6-gravitee-user-feedback-portal/c/22-graphql-policies is not clear to me if Gravitee will become also a GraphQL gateway (with GraphQL federation support) or if there will only the capability to proxy a GraphQL server and expose it as a REST API.
