### ISSUE TITLE
[policy] [rate-limit] Per-ip rate limiting

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#395]
Case : an api being used by smartphone or ajax applications.

### Expected Behavior
A rate limiter based  on caller IP would limit abuse without limiting other users.

### Current Behavior
With gravitee current versions it is difficult to avoid abusive use without harming all the legitimate users. This is because the api-key can be easily found in an ajax ou mobile app, and because black-listing an ip in gravitee is, today, a manual operation.

### Possible Solution
-Extend the per-key ratelimiter fonctionnality to memorize use per ip (this could be on a very short period, a few seconds is enouth), or
-create a new in-memory ratelimiter (independant on each gateway). The calls timestamps would be stored in a list for 2 seconds. Each subsequent call could then be checked against that list.

### Your Environment

* Version used: 1.2

Thanks,
Anselme

**Comment by brasseld** [comment]
Hi @AnselmeDewavrin,

FYI, version 1.2 is not yet released ;) So I expect you're using Gravitee.io API Management 1.1.x

The first solution you propose is easier than the second one since we already have the rate-limiting / quota policy based on the remote (consumer) IP for keyless API plan (starting from 1.2.x).
So, IMHO, the most simple solution would be to improve rate-limit / quota policy configuration by adding a new property to specify the _key_ used by the rate-limiting algorithm. This key must be:
* The remote IP
* The user ID (apikey, OAuth2 bearer, ...)

WDYT ?

**Comment by AnselmeDewavrin** [comment]
Hi,

The ip rate-limiter for keyless plans is exactly what is needed for apis accessed from mobile devices.

Thanks a lot,
Anselme

**Comment by barrycheng** [comment]
@brasseld How to implement the access frequency limit for a single IP?

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/issues/issues/4128
