### ISSUE TITLE
[management] Multiple versions of some swagger dependencies on the dist

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4120]
<img width="356" alt="Capture d’écran 2020-07-20 à 18 28 50" src="https://user-images.githubusercontent.com/1580262/87962114-fd415f80-cab6-11ea-83ef-e5cb1c139697.png">

**Comment by phiz71** [comment]
We need swagger 1.6.1 to generate our management API swagger from annotations and we need swagger 2.0.9 when creating API from swagger file.
If we could generate an OpenAPI v3 descriptor instead of swagger v2, maybe we could use a unique version of swagger libraries.

https://stackoverflow.com/questions/57877466/how-to-generate-oas-yaml-file-from-sources-annotations-using-swagger-3-x

**Comment by aelamrani** [comment]
We have to check if it still occurring with the changes provided by https://github.com/gravitee-io/issues/issues/4349

**Comment by phiz71** [comment]
To solve this issue, we must generate an OpenAPIv3 instead of a Swagger v2. As this is a breaking change, I move this issue to the APIM 3.5.0 milestone

**Comment by Andy2003** [comment]
I have a draft for the migration to open-api v3 pushed to https://github.com/Andy2003/gravitee-management-rest-api/tree/fix-swagger2. The branch contains additional changes for https://github.com/gravitee-io/issues/issues/4475 as well. As soon `3.2.x` is merged into master, I can rebase and cherry pick the open-api adjustments into an extra PR to resolve this Issue.

**Comment by brasseld** [comment]
Hey @Andy2003 

Thanks for your amazing stuff on Swagger and Gravitee.
I would like to learn more from you to understand why you   contribute to Gravitee. Can you contact me: david.brassely (at) graviteesource.com 

Thanks again,

**Comment by phiz71** [comment]
Hi @Andy2003 , I plan to review your PR next week. Until then, could you please rebase your branch on master ?

**Comment by Andy2003** [comment]
@phiz71 can you merge 3.0 into master before please?

**Comment by phiz71** [comment]
I've just realized that it is the swagger lib that include multiple version of itself.
![image](https://user-images.githubusercontent.com/13161768/100216800-01710400-2f13-11eb-9a63-4b9bd4767439.png)
It is necessary to be able to parse previous versions of openapi specification.

However, IMHO, it is a good thing to expose openapi instead of swagger. So all the work you've done @Andy2003 is not vain ;)

**Comment by phiz71** [comment]
For this release and in this issue, we will focus on the gravitee-management-rest-api modification.
We have to work from the branch of @Andy2003.
The remaining tasks are:
- rebase on master
- get ride of the wrapping of enum in queryparams. We can use the @JsonCreator annotation to handle upper and lower case.
