### ISSUE TITLE
[gateway] unauthorized message changed

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#434]
In 1.1.0 version, when i call an api without apiKey, an 401 error with message below was returned:
"message": "No API Key has been specified in headers (X-Gravitee-Api-Key) or query parameters (api-key)."

It helps users to know how to use api-key.

In 1.2.0, message is just:
 "message": "Unauthorized",

It will be nice to keep older message

**Comment by brasseld** [comment]
Hi @vdelattre, the problem is as follow:

In versions previous to 1.2.0, there was a single way to authenticate incoming HTTP calls, so we know that it was a security issue from api-key policy.
But this is not the case anymore starting from 1.2.0 where the API publisher has the ability to choose a security type per API plan. So, in this context, we have no way to know if the incoming HTTP call is relative to api-key or keyless or (later) to OAuth2.
Also, it can be considered as a security issue to provide too much informations to consumers in case of unauthorized request.

Is the explanation ok for you ?

**Comment by vdelattre** [comment]
OK, i understand
