### ISSUE TITLE
[policy] [quota] Inconsistent body for Quota at V3.2

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4345]
#### Context
After I have upgraded from version 3.1 to 3.2 I have experienced an inconsistent behavior of management-api for quota.

### Expected Behavior
The quota->limit and quota->periodTime numeric values to be either acceptable as STRING **or** INT. 

### Current Behavior
quota->limit is accepted only as STRING whereas quota->periodTime only as int. This makes the body inconsistent. Two numeric variables are accepted as different types. This behavior have been introduced with the new version of gravitee ( 3.2 ) and have not been present in ( 3.1 ) 
```
    {  "addHeaders":false,
       "async":false,
       "quota":{
          "limit":"100",
          "periodTime":1,
          "periodTimeUnit":"SECONDS"
       }
```

### Possible Solution
Make quota->limit and quota->periodTime consistent by making them one type.

### Steps to Reproduce (for bugs)

- Try adding a quota by updating api via managament-api with quota->limit as int
- Try adding a quota by updating api via managament-api with quota->periodTime as String
- Ensure a testing framework to test all policies before every release

### Your Environment

* Version used: 3.2

**Comment by bursauxa** [comment]
Hello, this is because `limit` supports SpEL, so it can not be any JSON type other than string.

On the other hand, `periodTime` does not, so it is a numeric.

**Comment by brasseld** [comment]
Hello @bursauxa 

I think @insertmike is right here.

The problem we are seeing is that, if you consider to call the management-api with existing requests to create API with rate-limit we are facing an error response from the management-api, because we are trying to push an `integer` for `string` property (does not respect the json-schema).

So IMHO, it looks like we'll have to reconsider the policy and provide two different properties to manage static limit and dynamic limit.  Unfortunately ...

**Comment by brasseld** [comment]
(I forget to mention that it works well from the UI.)
