### ISSUE TITLE
[portal] redoc does not use gateway url but portal url

### ISSUE THREAD

**Issue by YoranSys** [gravitee-io/issues#4389]
### Expected Behavior

When we use redoc, the calculated link doesn't use the gateway uri but use portal link. 

![image](https://user-images.githubusercontent.com/11197007/95183757-b403d080-07c6-11eb-825c-7ef33128036d.png)

### Your Environment
* APIM Version used: 3.X

**Comment by jhaeyaert** [comment]
Hi @YoranSys, this issue seems related to the openapi descriptor you use. I think you don't have `host` in your descriptor right ?
Going further, I noticed that you have a possible workaround. Just go to your swagger page configuration, and choose `Swagger-UI` viewer. This will "unlock" some settings and will allow you to specify your own base url (or use the default entrypoint).

![image](https://user-images.githubusercontent.com/5955401/95318468-e5e46800-0896-11eb-8d78-c80c11f475fd.png)

Before saving, switch back to `Redoc` viewer then refresh your portal documentation. You should have the right url.
I'm aware this is a weird workaround... but I think it will do the job until I prepare a PR allowing to specify these options for both swagger and redoc.
