### ISSUE TITLE
[management] Typo in deprecate enum token

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4414]
### Context
Path: ```MANAGEMENT_URL/apis/API_ID/plans/PLAN_ID/_depreciate```

### Expected Behavior
The deprecate enum token is accepted as: "_depreciate"

### Current Behavior
The deprecate enum token is accepted as: "_deprecate"

### Possible Solution
Change _depreciate to _deprecate

### Context
This can cause a bug that can be hard to find when integrating with management-api.

### Your Environment
Version used: 3.1.4

**Comment by aelamrani** [comment]
Hi @insertmike,

I usually use `deprecate` to specify something as not wishing to be used in the future, because we want to remove it.

So IMHO, I don't think it is not appropriate.

Maybe you can explain more the issue here, and why we should use `depreciate` for this case?

Regards

**Comment by insertmike** [comment]
Sorry, this is my wrong, I didn't know the meaning of depreciate. I am closing the issue as it is inappropriate.

**Comment by aelamrani** [comment]
Hi @insertmike 

I just read again your issue and specifically the solution your provide, and checked the source code and find out that we are exposing the .../:planId/_depreciate and you are right we should be consistent and change this for /_deprecate.

See https://github.com/gravitee-io/gravitee-management-rest-api/blob/c3115398fc4eff3fb866d085a53624b0bce97e53/gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiPlansResource.java#L269

So I reopen this issue so that we will adapt this in a minor future version as it is a breaking change. We will continue to expose the old path (_depreciate) but it will be deprecated 🙃  and removed on a futur major version.

Thanks for pointing
