### ISSUE TITLE
[policy] [rate-limit] Rate limited header

### ISSUE THREAD

**Issue by Frintrop** [gravitee-io/issues#446]
We have a plan containing quota and rate limits.

Only X-Quota headers will returned:

X-Quota-Limit: 10000
X-Quota-Remaining: 9987
X-Quota-Reset: 1489524270

Must we explicit add a Rate Limited policy to get X-Rate-Limit headers  ( "Add response headers") in response ? Therefore rate limited defined per plan will overwriten ?

**Comment by brasseld** [comment]
IMHO, the best solution will be to let the `api publisher` to choose if he wants to add quota or rate-limit headers when configuring policies in the plan configuration.
We have to add a checkbox in the UI for this, it could be part of a new ticket (or just this one if it's convenient to you).

Rate-limited defined per plan is not overridden, we are executing both. And you will probably ask me why ? Because at the plan level, rate-limiting is applied to all paths while at the api level, we are applying rate-limiting for a specific path only (but, for sure, this path can still be /* to handle all paths....).

**Comment by Frintrop** [comment]
We can take this issues for a feature request if u like,too.

**Comment by brasseld** [comment]
There is an option to return HTTP headers when defining rate-limit / quota at the plan level.
