### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4565]
The bundle size has increased from 249M to 307M since the release 3.0.0 to the 3.3.0.

- [x] Remove `jetty-alpn-agent` from the GW, no more used for JDK 11
- [x] Remove vertx-grpc dependency `gravitee-gateway-http`
- [x] rxjava2 & vertx-rx-java2 as a default dependency for node
- [x] remove rxjava2 & vertx-rx-java2 from policies: quota - ratelimit - spike arrest
- [ ] `gravitee-gateway-services-ratelimit` based on hZ instead of ehcache
- [x] Remove reactor-* dependencies from repository-mongo
- [x] Remove freemarker from notifier-api (transitive dep for the GW)
- [x] Remove bcpkix-jdk15on from ssl-enforcement

**Comment by brasseld** [comment]
API Gateway:

* Remove vertx-grpc dependency `gravitee-gateway-http`
* rxjava2 & vertx-rx-java2 as a default dependency for node
  * remove those dependencies from policies: quota - ratelimit - spike arrest
* `gravitee-gateway-services-ratelimit` based on hZ instead of ehcache
* Remove `gravitee-policy-soap-validation` from default bundle
* Remove reactor-* dependencies from repository-mongo
*
