### ISSUE TITLE
[policy] Policy instance creation rules

### ISSUE THREAD

**Issue by asafm** [gravitee-io/issues#460]
* Gitter chat doesn't seem to work so I'm resorting to open an issue here to ask a question
* gateway repository doesn't have issues tab enabled from some reason so I'm resorting to open the issue in this unrelated repo.

When I create a Policy plugin I have my FooPolicy class. What are the rules regarding the instance creation of this class. Will you create only a single instance of it? Or maybe one per request? 
I'm asking this to understand whether I can place some sort of cache for my policy data and I need to know there is only one single cache, especially since I will have a thread I will initiate there to update the cache.

**Comment by brasseld** [comment]
Hi @asafm,

1. We will have a look to the Gitter chat as soon as possible.
2. We have disabled issues tab for all repositories to concentrate all the issues into a single repository, so don't worry, you're on a good way.

About policy instantiation, a new policy instance is created per request. More, I would say it is not correct because if you are using policy multiple times in the request or response policy chain, you will have more than one policy instance.

If you are defining static field, the scope will be relative to the a single API (which has its own classloader) and will not be shared with others APIs.

Now, if you want to maintain a cache, you can use something we call a `Resource`. The lifecycle of the `Resource` is linked to the API lifecycle. So, when API starts, linked resources are started. When API stops, resources are also stopped.

The best for you is to have a look to our cache resource: https://github.com/gravitee-io/gravitee-resource-cache
And its use from the cache policy: https://github.com/gravitee-io/gravitee-policy-cache and mainly from: https://github.com/gravitee-io/gravitee-policy-cache/blob/master/src/main/java/io/gravitee/policy/cache/CachePolicy.java#L76
This way, you will be able to maintain the same cache between all policy instances.

Hope I'm clear enough. In any case, feel free to ask us, we will be happy to help you.
Finally, we know that we have to complete the documentation with those things, sorry for that...

**Comment by NicolasGeraud** [comment]
Hi @asafm 
Do you have enough informations ? Can I close this issue ?

**Comment by brasseld** [comment]
@NicolasGeraud No. We have to complete documentation with these explanations.

**Comment by NicolasGeraud** [comment]
moved to gravitee-io/gravitee-docs#69

**Comment by plsstephenson** [comment]
@brasseld Please can you confirm this is covered by this doc: https://docs.gravitee.io/apim/3.x/apim_policies_cache.html and https://docs.gravitee.io/apim/3.x/apim_publisherguide_design_studio_create.html#create-resources so I can close the issue? If anything is missing, pls let me know.
