### ISSUE TITLE
[portal] Override the main sentence in the homepage

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4856]
Allows to override the first sentence displayed on the homepage of the portal.

The need here is to update the homepage title:
![Capture d’écran 2021-04-09 à 13 51 23](https://user-images.githubusercontent.com/1580262/114175931-d5db3d00-993a-11eb-910f-a075b71be6ee.png)

We should be able to override this text from the console on portal settings.

Scenario:

- [ ] Test than we can remove this phrase
- [ ] Test than we can change the text

**Comment by larsnaesbye** [comment]
Much appreciated.

**Comment by gcusnieux** [comment]
![Capture d’écran 2021-04-09 à 09 07 17](https://user-images.githubusercontent.com/1457497/114142299-132bd480-9913-11eb-90db-5d3f3898abc4.png)

**Comment by patelami** [comment]
env: nighty

As a user, I should be able to add customer home page title **PASS**

If the `override homepage title` is set to off, then the default title is` Unleash the power of your APIs.` **PASS**

As a user, I should be able to set the override homepage title to 1 without specifying any values for portal homepage title **PASS** 


@aelamrani: Please can you confirm that the following functionality is intentional (the following scenario is a feature and not a bug)

Given I have set the feature `override homepage title` to on
And I do not provide any value for the `portal homepage title`
Then I don't see any title on the portal (i.e the default title will disappear)

**Comment by aelamrani** [comment]
Yes i confirm, as described in the issue we should be able to remove this title

**Comment by gustavovalverde** [comment]
@aelamrani if the option shown here https://github.com/gravitee-io/issues/issues/4856#issuecomment-816464883 was added. Is not longer visually available.

**Comment by aelamrani** [comment]
@gustavovalverde which version are you using? I can see the option on our nightly env: https://nightly.gravitee.io/#!/environments/DEFAULT/settings/portal

**Comment by gustavovalverde** [comment]
I'm using 3.7.3

**Comment by gustavovalverde** [comment]
Oh, nevermind. I see this was included in 3.8.
