### ISSUE TITLE
[management] Contact subscribers as an API publisher

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#4896]

**Comment by phiz71** [comment]
Maybe this just needs some UX since it already possible to contact subscribers.
Indeed, in the "message" menu of an API, if an API Publisher select the role "PRIMARY_OWNER", it will send a message to the primary owners of applications that have subscribed to this API.

![image](https://user-images.githubusercontent.com/13161768/110705319-85b37280-81f6-11eb-8ac9-b0ba397b9fa8.png)

**Comment by aelamrani** [comment]
- As a subscriber, I should receive the message sent to the API subscriber. PASS
- As an owner but not a subscriber, I should not receive the message sent to the API subscriber. FAIL

To be consistent, we should change the case of "Api" to "API" here:

<img width="520" alt="Capture d’écran 2021-04-12 à 07 29 55" src="https://user-images.githubusercontent.com/1580262/114345008-3350d300-9b61-11eb-9e13-3dac5b98a0d7.png">

Wondering if the following bug has been introduced by this feature: https://github.com/gravitee-io/issues/issues/5395

**Comment by gcusnieux** [comment]
@aelamrani I don't reproduce, my test:
  - Create an API with api_key security
  - Create user1 and app1
  - Create user2
  - Create a group with user1 and user2 and "Associate to existing apps"
  - Subscribe to the api with user2 and app1
  - Send a message to API Subscribers
  - Only user2 receive the message
