### ISSUE TITLE
[management-ui] Calendar widget is not accurate

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5027]
![widget_date](https://user-images.githubusercontent.com/133094/107205270-f8fe7480-69fd-11eb-967f-d4c788f3c1e7.png)

**Comment by gcusnieux** [comment]
In previous versions we had already had a problem of the same kind. https://github.com/gravitee-io/issues/issues/1684

We got around it by adding an en-GB locale to have the days in the same order.
https://github.com/gravitee-io/gravitee-management-webui/commit/38d149d89925f8f1e6cd66c8a8a7f00d03cb84df

But on a fr browser the months were in French and the days in English.

Since the removal of i18n support https://github.com/gravitee-io/issues/issues/4485, the problem we can use the default locale 'en'.
