### ISSUE TITLE
[management] improve /apis performance

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5045]

**Comment by jhaeyaert** [comment]
Below is a list of some quick & dirty improvements that have been performed. 

### Improvements

List of improvements are more consequent than expected so I tried to split the actions performed into global, management console and portal.

**Global**:
- Adding of volatile data (roles, users, users metadata and parameters) in the Gravitee context request cache to avoid fetching same data multiple times during the same Http request
- Adding of pageable `apiService.search` and `apiService.find` methods
- Rework of `apiService.getPicture` and `apiService.getBackground` method to avoid loading unnecessary and costly data of the api when we just want to return the image url.
 - Rework of `TaskServiceImpl.getApisForAPermission` to load only api ids of a group and avoid loading all of unnecessary api's data.

**Management console improvements**:
 - Adding of `/apis/_paged` and `/apis/_search/_paged` rest api routes to be used by the management console to avoid loading all the apis especially when the user has access to a lot of apis. These routes will probably be reintegrated the original ones later (because it will cause a breaking change).
 - Rework of the console apis screen to make the infiniscroll loads the apis with pagination
 - Adding of the cache-control on all api pictures http responses (at api, application and category scopes). Even undefined pictures are concerned to avoid the browser to try to fetch an empty picture every times. Picture hash is now based on the last api update date making sure the picture or background will be well reloaded by the browser if any update occurs.
 - Rework of `AbstractResource.canReadApi` to filter on the api we want to check the permission on instead of all the apis (especially when permissions are indirectly coming from the groups the user belongs to).
 - Rework of the audit screen to load the list of applications and apis in background instead of using the angular resolver mechanism which can block the display when there are a lot of applications and apis.
 - Rework of the create application screen to load the list of apis in background instead of using resolve which can block the display (used in step3 of the application creation).

**Portal improvements**:
 - Adding of the cache-control like it has been done on management side.
 - Rework of `ApiResource` and most of its sub resources (information, media, metrics, page, plan, rating) to only retrieve the targeted api instead of loading all the apis of the user and then filter the list to retrieve the wanted api.

### Remaining work

**Management console**:
 - The category screen (/#!/settings/categories) loads all the apis and can be slow depending on the number of apis and the type of user you're logged with (admin vs regular user)

**Portal**:
 - With a user having a lot of apis, the api list page can suffer of timeouts for the following reasons:
 	- The rest api offer a pagination mechanism but on the server side all apis (and all data around) are loaded, filtered in memory and then paginated.
 	- Some part of the code executed by the `filteringService` can be improved.
 	  Ex: `filteringService.getTopApis` takes an api list in parameter but makes a `topApiService.findAll()`. Furthermore, the `topApiService.findAll()` method takes a mapper and a filter which both trigger a call to `apiService.findById()` for each api.
    - On the api listing page, the UI makes several calls to `/apis` route:
    	- `/apis?size=1&filter=ALL&promoted=true`
    	- `/apis?size=4&-filter=ALL`
    	- `/apis?page=1&size=6&filter=ALL&promoted=false`
    	- `/apis?size=-1&filter=ALL`
    	As the pagination is made in memory, with a lot of apis, these calls can be quite time consuming and resource intensive.
- Portal categories page also suffers of latencies. The main reason is that all apis of the user are first retrieved (with all data, api by api) just to be able to calculate the number of apis for each category.
	- A quick solution could be to retrieve the categories and then invoke a `apiService.countPublishedByUser(criteria)` method with category id in criteria (to be develop).
- Application page has difficulties to load when a user has lot of applications (note: at first glance this case is less likely).
	- There is no pagination on this page
	- A big amount of data is fetch for each application and contributes to bad performances when the user has permissions on a lot of applications (these are the same data loaded when accessing a single application : owner, group, ...).
	- For each application the user has permission on, a rest call is made to get the number of subscriptions but a lot of data is retrieved to calculate this counter (api, plan, user, ...) and few of them are really useful
- I did had time enough to test all the feature, we must be sure that all features can be used without timeouts with a user having access to a lot of apis and applications (subscribe to an api, ...)

### Long term improvement tracks

Here are some tracks we could discuss on to continue to improve performances of the api.

- Rework on convert methods:
 	- convert methods could be refactored to only do mapping job. Currently convert methods are used at different places where, most of the times, there is no need to load other data.
 	- in the same time, we could work on fetch methods focused on only one type of data to fetch. Thus, it will be possible to select what data to fetch.
- work on count methods when it makes sense
- when dealing with a list of elements and we need to fetch some data, we could try to load data in batch mode instead of one by one
- it must be possible to retrieve apis and applications using server side pagination and sort. It may involves some database changes to be able to achieve real server side pagination.
- it could be interesting to allow to filter the data at api's level and propagate it to the service layer to avoid fetching unnecessary data.
