### ISSUE TITLE
[policy] How to access the properties defined in gravitee.yml from inside a policy?

### ISSUE THREAD

**Issue by YaytayAtWork** [gravitee-io/issues#511]
I have plans for a couple of policies that would benefit from accessing global configurations rather than having to have values set on each instance (JDBC URLs being one example).

There appear to be two ways to make this:
1. Define a resource plugin as well as the policy plugin.
2. Access the config properties from inside the policy plugin.

In attempting to do the second I've found that the executionContext contains an applicationContext and that applicationContext contains a Properties object representing the configuration.
Unfortunately the only way to access things in the applicationContext is via getComponent, which takes a Class argument, and if Properties.class is passed in it always returns System.properties.
If I hack around with a bit of reflection to access the applicationContext I can access the gravitee config using getBeanByName, but "hacking around with a bit of reflection" is not something I'd want to go live with :)

Would it be possible to have a getComponentByName method on executionContext?
Or is there a reason for not accessing the configs from inside a policy (I'm using statics to be sure I only run things once)?

Thanks.

**Comment by brasseld** [comment]
Hello @YaytayAtWork,

How many github account do you have ? ;)

[Here](https://github.com/gravitee-io/gravitee-policy-jwt/blob/master/src/main/java/io/gravitee/policy/jwt/JWTPolicy.java#L275) you can find a way to access configuration without having to hack "with a bit of reflection".

I'm not particularly happy with this kind of solution because, IMHO, it is preferable to avoid such dependency to Spring.

Anyway, it is a good "workaround" solution while waiting for a best one.

About JDBC, I would advise you to create a JDBC resource. It's pretty long to explain you all the reasons for this here and I would suggest you to ask the question on [gitter](https://gitter.im/gravitee-io/gravitee-io)

**Comment by YaytayAtWork** [comment]
Oops, same gravatar and I didn't even realise it was a different account!

Thanks for the workaround.

**Comment by NicolasGeraud** [comment]
@YaytayAtWork 

Perhaps you already know it : There is a company behind Gravitee.io called GraviteeSource (https://graviteesource.com).

We provide services and support of Gravitee.io.

Are you evaluating Gravitee.io for production ?

You can contact me at `nicolas.geraud at graviteesource.com` if you don't want to talk to that here.
