### ISSUE TITLE
[portal] example and schema imported from swagger document not displayed in portal

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5202]
### Current Behavior

While importing swagger document that contain examples and schema, they are not reflected in Portal.
They can be correctly seen in Preview page in Console.

### Steps to Reproduce (for bugs)
1. In Console, create swagger documentation page with the following file [swagger_apim.txt](https://github.com/gravitee-io/issues/files/6130573/swagger_apim.txt)

2. The preview correctly shows examples and schema

<img width="1545" alt="Capture d’écran 2021-03-12 à 15 16 41" src="https://user-images.githubusercontent.com/79909781/110952519-a094fc80-8346-11eb-803a-cea85aa75ad4.png">

3. Save and Deploy to Portal

4. Examples and schema will not display

<img width="1430" alt="Capture d’écran 2021-03-12 à 15 15 59" src="https://user-images.githubusercontent.com/79909781/110952629-bd313480-8346-11eb-9bb3-85d1127b511a.png">

* Version used: 3.6
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by jhaeyaert** [comment]
Testing the provided swagger descriptor on [https://editor.swagger.io/](https://editor.swagger.io/), I saw that the swagger is valid. However trying to convert it into openapi3 descriptor causes the same effect we have on the APIM portal.

This problem seems due to missing `type: object`  on schema definition of each path.

```yaml
paths:
  /brands:
    get:
      summary: All Brands
      description: Returns all Brands
      tags:
        - brands
      responses:
        '200':
          description: brand response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/Brand'
                   .....
```

Another workaround could be to define all schemas on the swagger v2 `definitions` part and use `$ref` instead.

Finally, we have to check if we can provide more consistency on how descriptors are interpreted on APIM management console side versus APIM portal (maybe we could keep original descriptor on both sides instead of convert it into openapi).
