### ISSUE TITLE
[management] VirtualHost HTTPS Management

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5452]
Use case :
 Use virtual-hosts entrypoints to pass consumers from an access URL "gateway.gravitee.company.com/myapi1" to a url "myapi1.company.com".
This feature works well in HTTP but currently not in HTTPS.

Queries : 
How to manage the certificates presented by the gateway to consumers in the case of a virtual-host.
DNS requested by API owners is not known in advance .
Have the ability to update the keystore dynamically via the UI for example
And delegate this management to the API producer (via a keystore by API proxy), or admin.

**Comment by jhaeyaert** [comment]
There is no such advanced features regarding the certificates management but I think you could either use a wildcard certificate such as `*.gravitee.company.com` either create a keystore with multiple certificates and enable `http.ssl.sni` on the gateway configuration.

**Comment by larsnaesbye** [comment]
This sounds a bit like the discussion we had after implementing SNI: we can now use a keystore with multiple certificates, but we can't use the various CNs in matching. 

If this is the case, it's high on our wishlist too :-)

**Comment by jhaeyaert** [comment]
Hi @larsnaesbye, I'm not sure to follow you. What do you mean by `we can't use the various CNs in matching` ?
Can you give us more details about your use case (or mention the previous discussion ?)

**Comment by larsnaesbye** [comment]
Sure. We requested SNI support because we had one keystore with several certificates in it. This was a fairly straightforward configuration of Vert.X SNI support. But this only let us select the right certificate.

We still have an issue of selecting the proper API depending on the san (for HTTPs) vs Host header (for HTTP).

But maybe I'm confusing this with the issue here.

**Comment by jhaeyaert** [comment]
Ok, may I ask you to open a dedicated issue and give us more details regarding your needs. I'm still confused because I don't understand why you can't select the proper api using the regular Host header (even in https with SNI enabled). May I ask you to give us a little example too (an example is better than a thousand words 😉).

Thx you for your time.

**Comment by larsnaesbye** [comment]
We already have a dialogue with David about this, based on an issue in Gravitee's official ZenDesk. So I think we're good for now :)
