### ISSUE TITLE
API Promotion

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5530]

**Comment by gaetanmaisse** [comment]
Technical questions: 
 - How are we doing/storing the relation between an API and its promoted version?
 - Is a promotion a new DB table with a many to many relation? or new fields in API object?

**Comment by gaetanmaisse** [comment]
There are multiples subjects to discuss when an installation with promotions to validate is deleted from Cockpit, for instance: 
 - What happens to the promotion on the source env? For now, they will be stuck in TO_BE_VALIDATED forever and it will block the ability to create a promotion if the env is linked to another installation
 - Should we keep the info about the source API of a promoted API? Or remove everything because it doesn't make any sense anymore
