### ISSUE TITLE
Export and Import API

### ISSUE THREAD

**Issue by Emmanuel35** [gravitee-io/issues#577]
I would to migrate a API description from a development environement to a Production.
How to do this stuff ?

### Expected Behavior
With a command line:
1. Export to a ZIP ?? a DIR ??
```
gravitee login -u user -p password -h http://gravitee-dev
gravitee export myapi
```
2.  Import a ZIP ?? a DIR ??
```
gravitee login -u user -p password -h http://gravitee-prod
gravitee import myapi
```

### Your Environment
* Version used: 1.5.1
* Operating System and version: OpenShift / Docker

**Comment by brasseld** [comment]
Hi @Emmanuel35,

There is only a single way to export / import an API definition: you must have to use the management-api and invoke it using curl.

We have currently no plan about a gravitee-cli because of a lack of time but we are sure that it would be really good to provide such tool to users. Your contribution on this topic is very welcome and will be greatly appreciated :)

**Comment by Emmanuel35** [comment]
Hi @brasseld ,

I will read this API usage.
Where is the API doc to do export / import ?

**Comment by brasseld** [comment]
By default, you can access Swagger definition at http://localhost:8083/management/swagger.json

And you should find something like `/apis/xxx-xxx-xxx/export` and `/apis/import`
