### ISSUE TITLE
[v3.9.X] The GW instance is no longer displayed on the nightly

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5782]
### Steps to Reproduce
1. Go to https://nightly.gravitee.io/#!/environments/DEFAULT/instances/

### Expected Behavior
The GW instance is displayed

### Current Behavior
The GW instance is not displayed

**Comment by larsnaesbye** [comment]
Can confirm this is a problem in 3.9.2.

**Comment by AskeFC** [comment]
We experience this as well on 3.9.2.
Also the same on 3.9.0 and 3.9.1.
And neither can we see any gateway information in the log, under a request when showing context.

**Comment by larsnaesbye** [comment]
We updated to 3.9.3, and the gateway still does not show. The same happens in the nightly.

**Comment by AskeFC** [comment]
It seems the not-showing gateway problem, persisted when doing inplace upgrade from 3.9.2 -> 3.9.3, of the containers with gateway & management api & management ui.
After completely removing all containers, also elasticsearch and mongodb, then starting the whole stack again, we can now see all gateways running 3.9.3.

So perhaps this bug is resolved, but another still remains when upgrading from 3.9.2 to 3.9.3.

**Comment by RachidKelidou** [comment]
Hi @AskeFC ,

Have you played this migration script ?

https://github.com/gravitee-io/release/blob/master/upgrades/3.x/3.9.0/mongodb/2-events-migration.js

Thank you.

**Comment by patelami** [comment]
My Apologies, I have accidentally deleted AskeFC's previous comment and I can not undo this action .

Env: nightly
Result: Pass

<img width="1588" alt="Screenshot 2021-08-09 at 15 58 13" src="https://user-images.githubusercontent.com/14215437/128728967-ebaaa91e-96ef-49ad-9d40-61b146d351fa.png">
