### ISSUE TITLE
Add `Try it` in Design Studio

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#5901]
UI + Rest API
1. Send to the rest API an API definition + the `try-it` request
2. Send the response to the FE via SSE (or do some polling if SSE isn't working as expected on Cockpit) -> polling
3. Add a button + loader

- [ ] REST API should return a `400 Bad Request` if API definition is not v2

Notes: 
 - Create a new tab "Try it"

**Comment by gaetanmaisse** [comment]
(8 with SSE/ 5 with polling)

**Comment by gaetanmaisse** [comment]
Moving to ready to test as it is available on the nightly env and a small demo has been done but there is no defined test cases so I don't really know what to do. cc @patelami

**Comment by LiliaEn** [comment]
The following test scenarios were performed on the current feature:
[ ] Imported a new API that has 2 policies ( a Mock Policy and a Json to Json Transformation) and Run a simple request (path-> /, method- Get)(without changing any details in the headers etc.)
[ ] Run the same request using Postman and compared the responses
[ ] Tested the above request using dummy headers (received the same response, not sure if it’s ok that headers are ignored, maybe an error should be displayed in this case, but the same happens when using Postman)
[ ] Tried to send a Post request without a body (received 403)
[ ] Disabled Mock policy and sent a Get request
[ ] Disabled Json to Json policy and sent a Get request
[ ] Disabled both policies and sent a Get request
[ ] Added a new flow with a Rate Limit policy that will restrict the nr of requests. Sent a few Get requests (received an error as expected)
[ ] Tested with a dummy path- got 404 
cc: @patelami
