### ISSUE TITLE
[gateway] [health-check] No more data reported

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#5916]
Since the upgrade to Vert.x 4, we are no more seeing HC at the API level.

Also, if we encounter DNS issue (or connection issue), the issue is no more reported as a failure.

**Comment by gaetanmaisse** [comment]
**Description**

Since the upgrade to Vert.x 4, health check calls targeting a non-reachable endpoint aren't considered in an error state.

**How to reproduce**

1. Select an API
2. Setup the health check to target a non-reachable endpoint 
3. Go to Health Check screen

    _Expected behaviour_:  in **Latest check** table you should see some unhealthy line, like this
![image](https://user-images.githubusercontent.com/4112568/127186289-b790efdc-4a0f-445a-93e5-b76404aa0569.png)
    _Current behaviour_:  **Latest check** table is empty 😱 

**Technical investigation**

With a health check targeting a non-reachable endpoint it ends up on: https://github.com/gravitee-io/gravitee-gateway/commit/ee24278f52ef344590d38fa6fae83a67bdf44af7#diff-27bb9c0241f62e47076[…]73b4cab76d097e88e3c03R201 with `succeeded to `false`. Then no extra things are done and the call is just ignored.
