### ISSUE TITLE
[Investigation] Using the same API key to consume multiple APIs

### ISSUE THREAD

**Issue by ibahloul** [gravitee-io/issues#5959]
**Description**

As a user, I want to use a single API Key with multiples APIs (related to a single App)

**Technical details**

Currently, when an application subscribe to an api using an ApiKey plan, it obtains a generated api key. This api key is then stored in the database and the value of the api key is used as the primary key ('id' field). Thus we have a guaranty that the api key is unique.

Apim allows to define a custom api key (feature needs to be enabled on the settings). In term of storage, custom api key are managed exactly in the same way that the generated one.

If we want to be able to reuse the same api key value for an application which subscribes to multiple apis, we can extend the custom api key feature. However, we need to address the following constraints:

- The api key value needs to be migrated in its own database field. The primary identifier needs to be unique, auto generated and stable.
- Business rules must be define regarding the reuse of a custom key and implemented on the management side (ex: can't use the same api key value for different applications, ex2: it should be possible to use the same custom key if application are not in the same environment, ...)
- On the gateway side, the api key information (plan, api, validity, ...) is currently retrieved by id (where the id is currently the api key value). The logic needs to change in order to retrieve the api key information by api key value and api id.

In a second step it will be necessary to think about renew / revocation of an api key used in multiple subscription and maybe allows the user decide either to revoke the api key on the current subscription either to revoke it for all subscription using the same key.

**Goal**

The goal of this issue is to:  
 - Check all the impact of having a single API Key: renew API key, CRUD on a subscription, manual edit
 - List everything that could impact the final estimate
 - Create subtasks

**Comment by marcambier** [comment]
### Step 1 : Database refactoring
**This step is a technical prerequisite for other steps : refactor the database, separing id from key.
There is no functionnal change, applications with still work like before**
	
Database : add new keys.key (string), which equals id for already existing records.
- jdbc : add liquibase script
- mongo : add js migration script

Model impacts :
- ApiKey -> add id
- ApiKeyEntity -> add id

Repositories impacts :
- JdbcApiKeyRepository.getId() -> return id instead of key
- ApiKeyMongo -> add id and set him @Id instead of key
- ApiKeyRepository.findById : now, it really finds by id, not by key (update parameter name)

Service impacts :
- ApiKeyServiceImpl.generateForSubscription : generate new key id via UuidString.generateRandom
- ApiKeyServiceImpl.convert : add id mapping

_If we want step 1 to work without step 2,
Implement ApiKeyRepository.findByKey, replace all calls to ApiKeyRepository.findById by ApiKeyRepository.findByKey (which returns the first found)_

### Step 2 : Handle duplicate API keys
**This step permits to use the same API key for multiple subscriptions of the same application.
There is no change of the frontend behaviour, so there are some limits :**
- 'custom api key' setting should be enabled, as user can set api keys
- user has to copy/paste an api key in order to reuse it when creating a new one (for example on subscription validation, or renewal)
- All renew/revoke/update actions on API keys are still unitary. For example, user will have to revoke X times the same API key in front.

Repository impacts :
- add ApiKeyRepository.findByKeyAndSubscription : optional, return first (should be one only)
- add ApiKeyRepository.findByKey : returns a list

Service impacts :
- ApiKeyServiceImpl.exists(key)
It actually checks if this key already exists.
Change it to ApiKeyServiceImpl.canCreate(key, application)
Returns true if key doesn't yet exists for another application, using ApiKeyRepository.findByKey
Callers have to provide application too on ApikeysResource.verifyApiKeyAvailability & SubscriptionService.process

- ApiKeyServiceImpl.findByKey(key)
Change it to findByKeyAndSubscription(key, subscription)
all callers should provide subscription too

- all callers of ApiKeyServiceImpl.revoke should provide subscription
1 call from ApiKeysResource, 1 call from ApiSubscriptionResource, 1 from ApplicationSubscriptionResource, 1 from SubscritionServiceImpl

- all callers of ApiKeyServiceImpl.reactivate should provide subscription
 1 call
	 
- ApiKeyServiceImpl.update : still calling apiKeyRepository.findById, but change parameter to use apiKeyEntity.getId() instead of key
all callers already call it with entity containing id

- ApiKeyServiceImpl.updateDaysToExpirationOnLastNotification, still calling apiKeyRepository.findById, but change parameter to use apiKeyEntity.getId() instead of key
all callers already call it with entity containing id
	
- ApiKeyServiceImpl.search : not impacted
	
Gateway impacts :

- ApiKeyPolicy:
Actual apiKey retreival is by id : executionContext.getComponent(ApiKeyRepository.class).findById(requestApiKey);
Now, we have to search it by apiID (available in executionContext) + key
We should probably avoid multiple database requests for performance, and just execute an unique request with JOIN on subscription & key.

### Step 3 : Handle grouped API key revokal/renewal/reactivation/update
**This step permits to handle API keys per group, in frontend and backend.
For example, when a user will validate a subscription, he will be able to choose a previously used API key for this application.
Or when a user will revoke an API key, it will revoke all other same API keys on other subscriptions.
This as not yet been analyzed.
We first have to determine the target user behaviour, and build wireframes**

**Comment by marcambier** [comment]
Updated previous comment, to update the "Gateway impacts" section.
I added some impacts : we need to refactor the way gateway puts api keys in cache (cause actually, it caches in then a map by key).

**Comment by gaetanmaisse** [comment]
@ibahloul the investigation is done should we close this issue and create a new one for the implementation?

**Comment by ibahloul** [comment]
It was already done, check the dependencies :p

**Comment by gaetanmaisse** [comment]
Perfect 👌🏻 , closing the issue then.
