### ISSUE TITLE
[management] Service Management Ecosystem (SME): API HTTP Connector Integration

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6132]
Dependance with #6130 - current behavior moving to plugin so we would have a dynamic form

### Expected behavior

As a developer, I want to use connector plugins to display more API backend options.

### Configuration form updates
- Some panels are collapsed : 
-- HTTP REQUEST
-- HTTP CONFIGURATION
-- HTTP PROXY 
-- SSL/TLS 
-- SSL-Client authentification
- Panels are collapsed independently 

<img width="1914" alt="Gravitee_io_Management-form" src="https://user-images.githubusercontent.com/3227037/133589518-f19a09f0-5ed1-41cb-85d4-59bc5c10c7d3.png">

**Comment by LiliaEn** [comment]
Please see bellow the scenarios that could not be properly tested and the questions.
- Http protocol 1.1 vs 2.0 -> How can a call be blocked in order to check that the protocols are applied correctly?
- Keep Alive-> How can a failed call be triggered to check this option properly?
- Http Pipelining- > How can this option be tested properly?
- Compression -> How can a compressed response be triggered?
- HTTP Redirects -> Tried to applied Dynamic Routing policy to trigger the redirect, but I was getting 400. Is there another way to trigger 3xx status codes?
- Http Headers-> Is there a header that can be used which will have an obvious outcome? Tried to use Connection or Content-type, but nothing special happens
- Proxy-> How can proxy types be tested? Do we have some test data to check that?
- SSL Options-> How can different key stores be tested?

cc: @RubenMMSantos @mouligno @gcusnieux

**Comment by gcusnieux** [comment]
> Please see bellow the scenarios that could not be properly tested and the questions.
> 
>     * Http protocol 1.1 vs 2.0 -> How can a call be blocked in order to check that the protocols are applied correctly?
 
https://api.gravitee.io supports protocol 1.1 & 2.0. If both works, it's okay !

>     * HTTP Redirects -> Tried to applied Dynamic Routing policy to trigger the redirect, but I was getting 400. Is there another way to trigger 3xx status codes?

You can try to use another API  with policy mock as endpoint and configure a 3xx status code

>     * Http Headers-> Is there a header that can be used which will have an obvious outcome? Tried to use Connection or Content-type, but nothing special happens

We can use https://api.gravitee.io/echo as endpoint and see headers in the response body 

>     * Keep Alive-> How can a failed call be triggered to check this option properly?

It will not be possible to failed. 

>     * Http Pipelining- > How can this option be tested properly?
>     * Compression -> How can a compressed response be triggered?
>     * Proxy-> How can proxy types be tested? Do we have some test data to check that?
>     * SSL Options-> How can different key stores be tested?

For all these options, the only way to verify is to monitor http calls between the gateway and the endpoint with a third party tool. 
We have automatic integration tests for that, we can consider that it works correctly.

> 
> cc: @RubenMMSantos @mouligno @gcusnieux

**Comment by LiliaEn** [comment]
[https://github.com/gravitee-io/issues/issues/6538](url)

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.13.0-SNAPSHOT.
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
The following issues were reported: #6487, #6514 , #6538-> might be invalid (still under investigation)
The ticket will be blocked until the bugs will be fixed.

**Comment by LiliaEn** [comment]
Above issues were fixed. Ticket is ready for release.
