### ISSUE TITLE
Remove the calls of getAuthenticatedUser() in ApiServiceImp

### ISSUE THREAD

**Issue by jgiovaresco** [gravitee-io/issues#6458]
In [ApiServiceImpl](https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java#L3139) we try to trigger a notification to the authenticated user. 

Unfortunately, with Cockpit command handlers there is no authenticated user, therefore it fails with a NullPointerException. 
I think it would be better to keep `getAuthenticatedUser` calls in resources and provide a userId in the service methods.

**Comment by a-cordier** [comment]
@LiliaEn steps to test the fix
  - create an API from cockpit API designer
  - enable notifications on updates at the API level
  - update the API from cockpit API designer

Expected behaviour: the update should work and the notification should be triggered

**Comment by a-cordier** [comment]
The authenticate method fails because it looks like the user has no role

`07:43:00.762 [vert.x-eventloop-thread-1] ERROR i.g.r.a.s.c.c.h.DeployModelCommandHandler - Error occurred when importing api [af949204-d565-41b1-8bb9-e087c719c741].
java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "io.gravitee.rest.api.model.UserEntity.getRoles()" is null`

**Comment by LiliaEn** [comment]
Tested on cockpit pre-prod env and the default APIM env v3.18.0 
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Notifications are triggered when making changes on the API Design in cockpit.
