### ISSUE TITLE
[gateway] Move errors from the response body to the logs associated with the transaction ID

### ISSUE THREAD

**Issue by lauthieb** [gravitee-io/issues#651]
Currently, when a request goes wrong, the error is returned in the response body.
It's not a good practice for the security of the solution.

### Expected Behavior

We can't see the details of the error in the body.

### Current Behavior

For example, when we do a request and get a status code "502 Bad Gateway", in the response body we receive : "http, basic, xx.x.mycompany.eu/10.x.x.x:1234 => myapi.mycompany.com:443, status: 403 Forbidden".

### Possible Solution

Instead of return the error in the response body, we should log it in association with the transaction ID.

### Context

For us, it's a security problem because anyone can see our gateway properties like original URL of the API and some confidential businesses errors.

### Your Environment

* Version used: 1.6.3
* Browser Name and version: Chrome - Version 58.0.3029.110 (64-bit)
* Operating System and version: macOS Sierra - Version 10.12.5

**Comment by lusoalex** [comment]
Hello,

I think it is not secure to reply with the IP of the proxy and the real backend target url too.
Plus in our context, the backend target is published on internet (that's why we use the proxy) so that means the api consumer knows now how to do direct calls...

Regards,
Alexandre.

**Comment by lusoalex** [comment]
Hi, in addition to this issue, errors & stacktrace should be kept into the gravitee logs.

Because as soon as we remove them from the body output, we still need to access to such information in order to be able to analyse what was going wrong.

In fact it would be really convenient to be able to go directly into a log (thanks to the transaction or request id) and see the details such as error message & stacktrace.

To resume : 

- API consumer should have a non detailed error (no stacktrace, no proxy information, etc...)
- API Manager should be able to access directly to the stacktrace, error message thanks to the transaction id. (using the api logs section)

Regards,
Alexandre.
