### ISSUE TITLE
[portal] application primary owner can't add members

### ISSUE THREAD

**Issue by marcambier** [gravitee-io/issues#6600]
As an application primary owner (not admin) ;
I can add members to my application on console.
But I can't on portal;

As an admin, it works.

**Comment by ThibaudAV** [comment]
Investigation:

- In the portal, in order to modify members, the user must have the permission to `R' on the `User' of all `Organization' roles assigned to him. (The final permissions is calculated by intersection)
It is also necessary to have the permission on the `MEMBER` of the role `Application` associated between the application and the user


- In the console we need to have the `MEMBER` permission of the `Application` role associated between the application and the user. But in the `Organization` part we need to have the permissions on `User` of at least one role associated to the user (the roles are cumulative).

In any case on the Backend I can modify the members.

A more global reflection is needed to know how the final permissions between the user and the application should be calculated in order to have the same behavior between the console and the portal. And the change should be made globally.

Currently with a consistent permissions management the problem does not occur 💭
