### ISSUE TITLE
[Investigation] Human Readable ID & Import/export API

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6858]
# Main objective

API consistency for Import/Export feature in order to add new features and develop a CLI.

### HR ID Implementations
- How do we create this ID
- Which entities need this HR ID (API, plans, pages, group, metadata ??)
- Should we use this HR ID to create HR url for resources ?
- how does that impact promote, rollback, duplication features ?
 
### Refactoring Import/export API
- Use the HR ID to distinguish Import/Export vs Promote behavior
- Prepare implementation plan & impacts

### Refactoring Promote
- Use the HR ID to distinguish Import/Export vs Promote behavior
- Prepare implementation plan & impacts

**Comment by marcambier** [comment]
On our first investigations session, we discussed about those improvements of our import process :
- High value improvements :
  - get rid of api.definition : generate definition only when pushing event to gateway
  - identify entities with same ID across all environments, to get rid of the "ID recalculation" process
	- use the current ID but add environment in PK
	- OR use a new functional ID
	- Blocking point : How to handle retro-compatibility ?
- Others :
  - split "recalculate IDs for new environment" process from import process
  - use a model as input instead of a string (handle different versions using a jackson serializer)
  - breaking change : stop matching entities by name : use IDs only

**Comment by marcambier** [comment]
Investigation is finished, so I close this ticket.
Implementation of crossId, and multiple import/export API improvements started within this ticket : https://github.com/gravitee-io/issues/issues/7003
