### ISSUE TITLE
Search through the logs with payload criteria, leads to an error

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#6912]
When searching through the logs of an api, if the payload criteria is used, and for an example we wanna use the method to sort the results, getting an error "Unable to retrieve logs" shown below:

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/149154066-e7e89d27-697a-4dcc-bcba-521f3e04fb7b.png](https://user-images.githubusercontent.com/89140082/149154066-e7e89d27-697a-4dcc-bcba-521f3e04fb7b.png))

 1\. Go to logs, search with a payload criteria
 2\. Click on method to sort the results
 3\. Error shown in the low right corner of the screen
 4\. See error

The logs from the management api:

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/149154916-52ae82e1-4c7c-4ce8-b5d2-065a5cd641d0.png](https://user-images.githubusercontent.com/89140082/149154916-52ae82e1-4c7c-4ce8-b5d2-065a5cd641d0.png))

Used versions: APIM 3.10.3, 3.12.4

**Comment by apoddany** [comment]
changing prio upon internal request

**Comment by gaetanmaisse** [comment]
After an investigation, here are some technical details:
 - when `Search in payloads` field is **empty** the Rest API is doing a request on the `Request` index, with all the filters selected + pagination + sorting
 - when `Search in payloads` field is **set** the Rest API is doing 2 requests: 
   - The 1st one is on the `Log` index to find the Id of request containing the search term in their body, it also have the pagination + sorting info. BUT the data aren't the same as in `Request` index, especially there is no `status` nor `method` field causing the request to 💥 when ES tries to sort the results
   - The 2nd one is on the `Request` index, with all the filters selected + pagination + sorting + the ids retrieved with the previous one

Also, fixing some sorting mapping won't fix the whole issue because it can have some size differences between `Request` and `Log` causing to retrieve more or fewer data according to the sorting used.
