### ISSUE TITLE
Test migration process from 3.10.x to 3.15

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6962]
As it's an LTS, we should review a full migration from 3.10.x to 3.15

**Comment by a-cordier** [comment]
Starting from a 3.10.8 and playing all migration scripts:

  - An error occurring on start up has been fixed by https://github.com/gravitee-io/gravitee-api-management/commit/98cf6e469561d8d5da5739bc62392f3cb9763d8e
  - Access for api1 and user looks good
  - Quick load test on GW with a couple of policies looks good as well
