### ISSUE TITLE
[Management] Make System Role permission editable

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7157]
## :rainbow: Feature

As an administrator, I want to be able to update permission for system role. 

## :sunrise_over_mountains: Additional information

- Organization Admin > Environment Admin > API Primary Owner / Application Primary Owner
- Organization admin role can not be edited
- Need a warning message to inform admin on potential impacts ? 

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [x] Given an org administrator role then i can update API primary owner permissions
- [x] Given an org administrator role then i can update Application primary owner permissions
- [x] Given an org administrator role then i can update Environment admin permissions
- [x] Given an env administrator role then i can update primary owner permission when i got permissions to update permissions.

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by a-cordier** [comment]
From a backend perspective
--
Most of the checks are made on permission, and there are very little static checks on the primary owner role (mostly, these checks assert that the Primary Owner Role remains unique)

Permission checks are bypassed for the Org. admin role in the permission filter, which means we can assume that a user with this role is able to perform any action that is lost due to the edition of the env admin or primary owner role

There are still some manual checks that are performed in the controller or service layer using `AbstracRessource::hasPermission` or `RoleService::hasPermission` which means we would need to refactor this methods to make then bypass the check if the user has the admin role on the organisation scope.

From a frontend perspective
--

About 20 static checks on the primary owner role that needs to be refactored to rely on permissions

Estimate
--
Editing the Primary Owner and Env Admin role is basically about removing one check from our backend code and a little bit more in the org settings component in our frontend code, but given the refactoring that needs to be performed, a 👕 L looks like a good fit to me

**Comment by omatthewsgravitee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---API-Management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/7157?planning-poker) with ZenHub @gcusnieux @a-cordier @RubenMMSantos @phiz71
