### ISSUE TITLE
[Portal] Portal notifications

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7256]
## :collision: Describe the bug
Portal notifications on the portal erase application notifications information.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Console > your application
2. Click on default mail notification and deactivate some notifications
3. Go to portal > your application
4. Go to portal notification and change notifications settings
5. Go back to console, both portal notification and email notification has been updated

![image](https://user-images.githubusercontent.com/3227037/157263758-5853e0e1-05a2-41ff-b221-a4b5f865d271.png)
![image](https://user-images.githubusercontent.com/3227037/157263811-c33f928d-4d0e-4020-b17d-d77178c36fff.png)
![image](https://user-images.githubusercontent.com/3227037/157263858-330cd031-48e2-4d5b-98c0-ea6c222902d9.png)

## :rainbow: Expected behaviour
Modification on the portal side should override only the portal notification.

## Current behaviour
it overrides all notifications from the portal

## :movie_camera: Useful information

- By default, all notifications are activated on the portal and none on the console 🤷‍♂️
- I can have several notification setup (various email triggered by various event) but they get override if i change something on the portal side.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.10.x +

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by ThibaudAV** [comment]
The behavior seems to be as expected 🤷‍♂️ 

In the code we can see that the merger between portalNotificationConfigService and genericNotificationConfigService is intended
https://github.com/gravitee-io/gravitee-api-management/blob/05a328043162825abd67227e7818f36955a09e42/gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationNotificationResource.java#L94
https://github.com/gravitee-io/gravitee-api-management/blob/05a328043162825abd67227e7818f36955a09e42/gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/ApplicationNotificationResource.java#L69


on the other hand it is not clear because at the update on the console side it only modifies one 
https://github.com/gravitee-io/gravitee-api-management/blob/2fb9f9376473c21d321bee96db391f4b53c90be0/gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApplicationNotificationSettingsResource.java#L127

It would be nice to clarify the feature before applying changes here

**Comment by mouligno** [comment]
i think this two tickets are related : 
- https://github.com/gravitee-io/issues/issues/3115
- https://github.com/gravitee-io/issues/issues/929

**Comment by mouligno** [comment]
Original behavior : 
- custom config notifier for application on console side
- as simple as possible on portal.

It's "normal" that modifications on the portal override settings from console, but does a user needs to configure on both side ? 

I close since it won't be directly fixed but would be part of insights regarding notifications management in further rework of the feature.
