### ISSUE TITLE
Accept-Encoding-Header is being deleted from the gateway

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#7512]
## :collision: Describe the bug
The Accept-Encoding-Header is deleted from the gateway, shown in the analytics as well.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to analytics/logs
2. Click on one of the calls
3. Check if the Accept-Encoding-Header is present in the headers of the gateway
4. See it missing

![image](https://user-images.githubusercontent.com/89140082/163334882-b2c75695-377b-4cac-bbc5-63687ee8bcbe.png)
woking one was 3.10.9

![image](https://user-images.githubusercontent.com/89140082/163334915-33e62731-0c08-4310-afe3-4962c2f2cf75.png)
3.15.7 non-working

**Comment by a-cordier** [comment]
Hi @zveljanoski,

An Architecture Design Decision has been made to avoid issues regarding content negotiation while proxying requests.

As a consequence, the `Accept-Encoding` header is not propagated to the upstream anymore by the gateway.

Here is the except of the ADR

> Decision
Because there are 2 different communications that are not related (client → gateway and gateway → backend) it is preferable to NEVER propagate the Accept-Encoding header defined by the client when the Gateway communicates with the Backend.

**Comment by gaeljw** [comment]
As per my understanding this change was brought by version 3.15.6.

I'm unsure about how Gravitee versioning works but IMHO this kind of change should not be included in a patch version (assuming semantic versioning). Or at the very least it should be documented in a changelog with emphasis on the breaking nature of it.
