### ISSUE TITLE
[Management] Audit event are not scoped by env

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7521]
On my cockpit organization with several environments, i've been seeing audit events for all environments instead of events specific for my current env.

### Additional informations

As you can see on the screenshots below, we are not on the same env but we got the same audit logs page : 

![image](https://user-images.githubusercontent.com/3227037/163538672-da866b3c-c8d9-4a08-8ea2-6ca13b6875d3.png)
![image](https://user-images.githubusercontent.com/3227037/163538699-0f682e2f-8cf8-46e6-b48f-53d408fc2eff.png)
![image](https://user-images.githubusercontent.com/3227037/163538747-2006d30d-a7ba-4bf9-a3ed-d5a7c878ed2b.png)

**Comment by RubenMMSantos** [comment]
issue verified and confirmed as fixed, Audit events are now scoped by envir. Triggered some events across 2 environments in order to confirm behaviour was as expected.
![Screenshot 2022-05-03 at 12.28.07.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/c31b12fe-164a-427e-9bb6-fc07d8ec1fb1)![Screenshot 2022-05-03 at 12.28.18.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/0b442ddc-9de5-4110-ba0e-6a182eff4bb4)
