### ISSUE TITLE
Internal server error on FIDO2 factor when attestation set to 'none'

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#7967]
### Expected Behavior
As a user, I should be able to successfully register and sign in using FIDO2 factor

### Current Behavior
Given I have set Attestation Conveyance Preference = none in web auth 
And I am trying to register FIDO2 factor 
Then I am getting internal server error

### Steps to Reproduce (for bugs)

1. Go to Settings > WebAuthn > Attestation Conveyance Preference > select None
2. Create a user
3. Enable FIDO2 factor and disable all other MFA
4. Initiate a login flow
5. Skip passwordless
6. Register for MFA - FIDO2 on the device using  finger print

### Your Environment

* Version used: 3.18
* Browser Name and version: chrome

**Comment by ashraf706** [comment]
This is a known issue that selecting `Attestation Conveyance Preference` to `None` throws "AAGUID is not 00000000-0000-0000-0000-000000000000!" error.

It seems our implementation is as per the document and the device should not populate the aaguid. But in this case the device (for an example the mac I am using) is generating the aagid. As a result the vertx library throwing the error.

We should handle the error more gracefully rather than the service not unavailable error.
