### ISSUE TITLE
[API Definition V4] Spike - API creation workflow v4

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8016]
## Global context

In order to fully support the Sync and Asynchronous API, the API creation workflow has been globally redesigned (UX + UI).

**Link to the mockups** : https://www.figma.com/file/ypt1ab4iyg1aEzYIwRiYFl/API-Creation-Workflow?node-id=841%3A4298
*NB : that is a mockup with full capabilities, current app will evolve (and design with it) as the features are integrated into the product.*

Main changes : 
- Support Async/Sync APIs
- Adaptive process regarding entrypoint selected
- Specific configuration per connector (entrypoint/endpoint) : need to be handle at connector level
- Ability to create resources from the workflow in order to allow the creation of JWT/OAuth2 plans
- Ability to create multiple plans
- API Summary available along the process in right column
- Link to the marketplace and leverage plugin capabilities (discover SME and connectors)
- Leverage Access Management in plan creation & API security section
- Leverage API Designer with a deisgn first approach or pulling an existing API design
- Global UI and interactions

## ❓ Pending questions

- Quid of the sync API since this API creation workflow is handling v4 api_defintiion ? Should we keep the existing workflow for sync API or integrate in a near near future Sync API management with v4 api_definition ?
- Migration to Angular or new screens ? 
- List of missing components / things that need to be adapt for early versions
- How do we handle the specific connector configuration ? Schema form duplicated ? 
- How do we handle the resource creation ? 
- Quid of the navigation through the different steps of the workflow in a non-linear way : discussed with UX team and we'll keep it linear for now in order to avoid complexity and make it evolve later if needed

**Comment by gaetanmaisse** [comment]
**Quid of the sync API since this API creation workflow is handling v4 api_definition ?**

We will keep the current creation workflow for sync API. As it was done for v1 and v2

**Should we keep the existing workflow for sync API or integrate in a near future Sync API management with v4 api_definition ?**

It's a product question

**Migration to Angular or new screens ?**

We will create new Angular components for the new API creation workflow and keep the existing one  for v2.

**How do we handle the specific connector configuration? Schema form duplicated ?**

We specific schema form

**How do we handle the resource creation ?**

It's a product question
