### ISSUE TITLE
[SME] US- entrypoint component

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8081]
## :rainbow: Feature

As an Async API Publisher, I want to define an entrypoint in order to expose my apis in order to transform incoming/outgoing messages.

## :sunrise_over_mountains: Additional information

[Original slab page with further information.](https://gravitee.slab.com/posts/sme-ik15ejld#h5xkw-poc)

### Note: definition for API Async/Sync EntryPointConnector

- An entrypoint is attached to a specific listener (http, subscription or tcp) and is responsible of dealing with incoming and outgoing data to the client. For example, SSE entrypoint should enable text/event-stream content-type on request and transform message from endpoint to SSE event.
- Responsible of dealing with the incoming requests data
- For Sync EntryPoint, could transform incoming data depending on the protocol (grpc sync)
- For Async EntryPoint, must transform incoming data to messages
- One implementation by supported top-protocol we could imagine have http-rest, SSE, WebSocket, grpc etc.

## :superhero: Acceptance criteria

- [ ] I can register a plugin entrypoint (mock one)
- [ ] I can retrieve a list of entrypoints through M-API
- [ ] Improve SDK to register entrypoint

**Comment by Sicofonia** [comment]
Suggestion for spike rewrite:

FEATURE TEXT:
As an Async API Publisher, I want to define an entrypoint in order to expose my apis.
To properly manage different kind of protocol for SME, a new entrypoint component must be introduced in order to properly transform either incoming or outgoing messages.

Note: definition for API Async/Sync EntryPointConnector
An entrypoint is attached to a specific listener (http, subscription or tcp) and is responsible of dealing with incoming and outgoing data to the client. For example, SSE entrypoint should enable  text/event-stream content-type on request and transform message from endpoint to SSE event.
Responsible of dealing with the incoming requests data
For Sync EntryPoint, could transform incoming data depending on the protocol (grpc sync)
For Async EntryPoint, must transform incoming data to messages
One implementation by supported top-protocol we could imagine have http-rest, SSE, WebSocket, grpc etc.

QUESTION:

- Do we need to introduce compatibility between entrypoint and endpoint? (Product)
- What's the impact of defining an entrypoint inside an API when types are different? (i.e. entrypoint supports subscribe operation, but endpoint doesn't? what should happen?)
- How do we resolve the API from the request? (i.e. how to link an specific API request (/products/create) to the right entrypoint). In other words, how does SME support multiple entrypoints (at the moment it is one entrypoint per API).
- As we introduce new entrypoint plugins, what's the impact of this? how does need to be created? Need to understand because there could be some UI impacts, that we can use for future stories (create plugin, list plugins).
