### ISSUE TITLE
[Async] [Kafka endpoint] Subscribe to topic

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8245]
## :rainbow: Feature

As an Async API Publisher, I want to subscribe to a specific topic using the Kafka connector to read specific messages.

## :sunrise_over_mountains: Additional information

- Create a consumer
  - bootstrap.servers
  - group.id (from transactional id ? #8037 )
  - key/value deserializer - default value 

- Subscribe to topic
  - topic name (1 or more, list to provide)
  - Out of scope 
    - partition 
    - offset 
    - heartbeat
    - commit mechanism ? auto commit. ?

- Close the consumer with client ended connection

Example of initialization - 
https://github.com/gravitee-io/gravitee-poc-sme/blob/master/src/main/java/io/gravitee/poc/sme/gateway/connector/endpoint/async/impl/KafkaEndpointAsyncConnector.java

## :superhero: Acceptance criteria

- [x] Given an async API with a kafka topic as endpoint Then I can process a message through the gateway When a new one lands in Kafka Topic

**Comment by guillaumelamirand** [comment]
Two PR are opened : 

1. https://github.com/gravitee-io/gravitee-api-management/pull/2379
2. https://github.com/gravitee-io/gravitee-gateway-api/pull/137

In order to test you can you use the attach file:

1. Run the docker compose
2. Create the api using the collection
3. Use the python file to publish new record
[https://app.zenhub.com/files/61280156/e99f5405-32d4-4dc0-bbcf-7f1d9e488aca/download](https://app.zenhub.com/files/61280156/e99f5405-32d4-4dc0-bbcf-7f1d9e488aca/download)

**Comment by LiliaEn** [comment]
Tested locally using 3.19.0 version
The following scenarios were covered:
- Create an API with sse entrypoint and kafka topic as endpoint
- Use the python file to publish new record
- Call the API and check that the message set in the python file is displayed

**Comment by LiliaEn** [comment]
Tested locally using 3.19.0 version
The following scenarios were covered:
- Create an API with sse entrypoint and kafka topic as endpoint
- Use the python file to publish new record
- Call the API and check that the message set in the python file is displayed
