### ISSUE TITLE
[Async] [Kafka endpoint] Publish to a topic

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8247]
## :rainbow: Feature

As an Async API Publisher, I want to publish to a specific topic using the Kafka connector.

## :sunrise_over_mountains: Additional information

- Create a producer
- push message to specific topic
- Authentification is out of scope 
- New endpoint plugin

Example of initialization - 
https://github.com/gravitee-io/gravitee-poc-sme/blob/master/src/main/java/io/gravitee/poc/sme/gateway/connector/endpoint/async/impl/KafkaEndpointAsyncConnector.java

## :superhero: Acceptance criteria

- [x] Given an async API with a kafka topic as endpoint 
- [x] Then I can publish a new record to my topic through my API

**Comment by guillaumelamirand** [comment]
Two PR are opened : 

1. https://github.com/gravitee-io/gravitee-api-management/pull/2379
2. https://github.com/gravitee-io/gravitee-gateway-api/pull/137

In order to test you can you use the attach file:

1. Run the docker compose
2. Create the api using the collection
3. Use the python file to publish new record
[https://app.zenhub.com/files/61280156/3d70b2c7-bc8a-404a-867b-66bd9d7d3803/download](https://app.zenhub.com/files/61280156/3d70b2c7-bc8a-404a-867b-66bd9d7d3803/download)

**Comment by LiliaEn** [comment]
Tested locally using 3.19.0 version.
The following scenarios were covered:
- Create an API with http-post entrypoint and kafka endpoint and a topic
- Create a plan+ publish and start the API
- Send a post request with a message and check on the Kafka Client UI that the message is displayed on the appropriate topic
