### ISSUE TITLE
[Async] Identify messages

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8262]
## :rainbow: Feature

As an API Publisher, I want my Async API to identify messages in order to deliver a high quality of service by sending events one and possibly resume to last message in case of loose connection (dependent of endpoint capabilities)

## :sunrise_over_mountains: Additional information

- For Kafka, ID could `<key>#<partition>-<offset>`
  - if `key == null`, generate `uuid`
- Implemented at endpoint level

## 🛑 Out of scope 
- Resume, replay... capabilities

## :superhero: Acceptance criteria

- [x] Given an Async API with an  entrypoint, i can received identified messages

**Comment by guillaumelamirand** [comment]
Could elaborate on how this should be work ?

The "resume" part couldn't be supported by SSE because this is endpoint responsability to consume data. In case of kafka, I assume we could find a proper solution to generate id from kafka record metadata (kafka record doesn't contain any id). but any on-the-fly messages protocol such as mqtt or jms couldn't implement those mechanism because the message could be in memory and then when consumed there disappear.

**Comment by guillaumelamirand** [comment]
https://github.com/gravitee-io/gravitee-api-management/pull/2436
https://github.com/gravitee-io/gravitee-gateway-api/pull/143

**Comment by LiliaEn** [comment]
The ticket will be tested when QOS will be merged to master

**Comment by LiliaEn** [comment]
Tested locally using 3.20.0 version
Messages get an uuid when qos is other  than "balanced"
![Screenshot 2022-10-25 at 08.30.39.png](https://images.zenhubusercontent.com/611a4ca72ea95c552dc9122c/ac534a21-f9f2-4abf-8bf5-932e5c0fda21)
