### ISSUE TITLE
[GKO] Improve the error handling

### ISSUE THREAD

**Issue by kamiiiel** [gravitee-io/issues#8301]
As of now, we handle all the errors in the same way while we need to distinguish between recoverable and non-recoverable errors while dealing with the K8S api server itself or when creating/updating ConfigMaps or calling Management API.

**Comment by ThibaudAV** [comment]
### Made Reconciling error

Here is an example of a Reconciling error scenario

- Update ManagementContext resource with bad BaseUrl OR Delete management-api pod to simulate a network error with it
- Update ApiDefinition (change the description for example)
- The operator will try to update the ApiDefinition but will fail because of the network error to contact management-api. The Processing Status will be set to Reconciling
- Fix ManagementContext resource with good BaseUrl OR Restart management-api pod
- The operator will try (each 5s) to update the ApiDefinition again and will succeed. The Processing Status will be set to Completed

### Made Failed error

Here is an example of a Failed error scenario

- Update ManagementContext resource with bad user credentials to simulate 401 error
- Update ApiDefinition (change the description for example)
- The operator will try to update the ApiDefinition but will fail because of the 401 error. The Processing Status will be set to Failed

The operator do not retry to update the ApiDefinition because it is not possible to fix the error without changing the ManagementContext resource (Manual action).
After fixing the ManagementContext resource. A new update of the ApiDefinition should be done by the user to retry the update.

**Comment by RubenMMSantos** [comment]
Errors are now more easy to understand and are distinguishable between recoverable and non-recoverable errors while dealing with the K8S api server itself or when creating/updating ConfigMaps or calling Management API
