### ISSUE TITLE
Unable to remove `Filter by status code` in analytics tab of the dashboard

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#8411]
# Describe the bug

When you add a filter in the analytics in the dashboard of the console, you can not remove it if you click the same status code again.

# To Reproduce

Steps to reproduce the behaviour:
 1\. Prepare a simple API with several different calls with different status codes.
 2\. Go to the Analytics tab in Dashboard
 3\. Scroll down to the chart for status codes and click on the statuses to set a filter.
 4\. Click the same status code again to remove the filter.

# Expected behaviour

When you click the same status code for a second time it should remove the filter for the code.

# Current behaviour

When you click the same status code for second time it is not removing the filter for the code. It has to be scrolled up to the top of the page and removed by clicking on the X on the filter.

# Useful information

[https://user-images.githubusercontent.com/98313939/188402910-1b766bd1-56ba-4b55-8bab-b8e82bc6b408.mp4](https://user-images.githubusercontent.com/98313939/188402910-1b766bd1-56ba-4b55-8bab-b8e82bc6b408.mp4)

**Comment by ytvnr** [comment]
We will close the ticket because:
- there is still a way to remove filter (as done in the video)
- this is non blocker
- we are currently reworking those screens (there are already some PRs: https://github.com/gravitee-io/gravitee-api-management/pull/3359 and https://github.com/gravitee-io/gravitee-api-management/pull/3364)
