### ISSUE TITLE
Improve gateway behavior with Redis rate-limit configured and Redis is down

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#8545]
# Describe the bug

When gateways are configured with redis for ratelimit policies (sync or async), if the redis server is down, then the gateways start being unresponsive with threads requesting ratelimit counters blocked (ie vert.x-eventloop-thread-3,5,main)

# To Reproduce

Steps to reproduce the behaviour:

*   setup an environment with redis for rate limit
*   create an API using ratelimit policy
*   stop the redis server instance
*   trigger a lot of requests for this API
*   check the content of the logs and responsiveness of the gateway

# Expected behaviour

Have the gateway to keep handling requests if redis is down and test redis connectivity periodically and avoid blocking thread

**Comment by gaetanmaisse** [comment]
## Rate Limiting with Redis

At the moment, the Redis implementation of the Rate Limit plugin is using Lettuce Spring Data which internally provides a connection pool to connect to different types of Redis setups (Standalone, Sentinel)
and a synchronous client. An asynchronous and reactive client is also available, but we are currently not using it and it didn't get any update for 3 years.

On its side, Vertx also provides a Redis client, asynchronous and reactive by design. It also provides a connection pool and supports different types of Redis setups.
Here are a few pros of using Vertx Redis client instead of the existing one:

- The Vertx client also provides the same functionalities for different Redis setups (Standalone, Sentinel …), similar to the Spring data client.
- Vertx Redis Client is an asynchronous client and shows that it performs better in all the tests (almost twice the existing client).
- It relies on Vertx and fits very well with the rest of the Gravitee ecosystem.
- It reduces the final compiled zip file significantly (From 10 MB to just 150KB), so the Redis repository can easily be added to the list of plugins included in the default bundle. Currently, this plugin isn't included by default because of its big size, so it needs to be downloaded manually by users.

### Performance tests

#### Test setup

Tests were done locally since the idea was only to show an improvement.
The configuration used for the test was :

- Mac M1 with 32Gb RAM
- Gateway 3.21.0-SNAPSHOT (-Xms256m -Xmx256m and gravitee_reporters_elasticsearch_enabled=false) and 2 http instances
- Redis 7.0.8
- Spring Data Redis 2.6.4
- Vert.x Redis Client 4.3.8
- Simple API with API Key
- Backend: a local http-echo server
- Injector: k6 with 5 stages of 60s (10 VUs, 50 VUs, 100 VUs, 250 VUs and 500 Vus)
- Grafana and Prometheus to collect and visualize each run

#### Rate Limit plugin deactivated (baseline for comparison)

![img](https://user-images.githubusercontent.com/4112568/228154116-aeac0f54-67b5-49c8-b540-6c138dedd88e.png)

Results:

| Virtuals Users | P99 Response time |
| -------------- | ----------------- |
| 10             | 2.8ms             |
| 50             | 10ms              |
| 100            | 15ms              |
| 250            | 32ms              |
| 500            | 55mss             |

#### Rate Limit plugin activated using the Spring Data Redis Client (Redis in standalone)

![img_3](https://user-images.githubusercontent.com/4112568/228154158-69702a09-63ce-4d44-92e6-b2eaafe3c98a.png)


Results:

| Virtuals Users | P99 Response time |
| -------------- | ----------------- |
| 10             | 12ms              |
| 50             | 48ms              |
| 100            | 94ms              |
| 250            | 212ms             |
| 500            | 729ms             |

#### Rate Limit plugin activated using the Vert.x Redis Client (Redis in standalone)

![img_4](https://user-images.githubusercontent.com/4112568/228154212-b4758636-eaa2-48de-b55e-75b1bfa4d9e2.png)


Results:

| Virtuals Users | P99 Response time | Difference with Spring Data Redis Client |
| -------------- | ----------------- | ---------------------------------------- |
| 10             | 5.6ms             | 6.4ms ; **decrease of 53%**              |
| 50             | 11ms              | 37ms ; **decrease of 78%**               |
| 100            | 22ms              | 72ms ; **decrease of 77%**               |
| 250            | 39ms              | 173ms ; **decrease of 81%**              |
| 500            | 67ms              | 652ms ; **decrease of 89%**              |


### Stability tests when Redis is down

#### Rate Limit plugin activated using the Spring Data Redis Client (Redis in standalone)

Status code over time
![img_7](https://user-images.githubusercontent.com/4112568/228154237-319d8185-e2ae-407a-a4c1-e7e2eb9e5516.png)


HTTP Response time over time
![img_8](https://user-images.githubusercontent.com/4112568/228154256-7be70935-d050-47c8-8741-a87a4d7ee688.png)


#### Rate Limit plugin activated using the Vert.x Redis Client (Redis in standalone)

Status code over time
![img_9](https://user-images.githubusercontent.com/4112568/228154278-aa760fdf-12bc-4ed0-91fa-38840c71aa3f.png)


HTTP Response time over time
![img_10](https://user-images.githubusercontent.com/4112568/228154291-2f443fd4-bd5a-4471-a94d-9ce517946b15.png)
