### ISSUE TITLE
[portal] Import documentation using an URL

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#86]
Currently, API publisher has the ability to provide documentation (swagger, raml, markdown) by copy and paste content into a text area.

It would be nice to put a simple URL instead of text content.
For example:
- I would like to provide an URL to Swagger descriptor
- I would like to provide an URL to a GitHub or GitLab page

**Comment by NicolasGeraud** [comment]
Actualy we could store the content of a file. This mean we could easily get content from url and store it.
That way, documentation does not depend on a third party (typically your VCS).

But on the other hand, the documentation will not evolve with your commits.

So I think we need to get the content each time a user want to braowse the API documentation.
This mean that we have to store authentication informations to access private repositories.

Do you think we need to put this authentication in the gravitee.yml of the rest-api or this must be a per api configuration ?

**Comment by NicolasGeraud** [comment]
gitlab does not support http authent to retrieve files. We need to use their API to get the content of a file.
This will be performed by the rest-api on a scheduled job.

So when you want to add a page from a file hosted on git, you must provide:  
 - The provider (github, gitlab, bitbucket, ...)
 - The repository name
 - The branch/tag
 - The path to the file you want to add

The rest-api must have credentials to log on the provider (those credentials will be stored in `gravitee.yml`)

Like a jenkins job, the rest-api must poll the git repository to check if there is something commited since last polling.

The content of the file will be stored in gateway on each change.

What do you think ?

**Comment by brasseld** [comment]
I'm not sure about what you mean by "_The content of the file will be stored in gateway on each change._". **Gateway must not be involved in this feature**.

Also, why do you want to generalize the concept of URL to only git ? Perhaps I have to update the ticket's title to something more relevant to resources "retrieving".

The goal is to be able to use an external provider to get back resources to complete documentation automatically. A provider can be:
- gitlab (with all required informations to get data)
- github (with all required informations to get data)
- an HTTP url

Agreed for credentials, gravitee.io must be seen has a "technical user" for "providers".

**Comment by NicolasGeraud** [comment]
typo s/gateway/gravitee-repository/

**Comment by NicolasGeraud** [comment]
I'm aggree that git is not the only "external provider", but I think it's the provider n°1 because most of the time, raml/swagger documentation will be stored on git.

**Comment by brasseld** [comment]
Again, not sure...

Provider n°1 should be simple HTTP URL ;-)
