### ISSUE TITLE
[Policy - Assign Content] AC Policy adds comma to a number above 1000 send in Json body in request

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8702]
## :collision: Describe the bug
If we send a number as a number and not a String with quotes AC policy will add comma if the number is above 1000. 

![image](https://user-images.githubusercontent.com/57534152/205873788-758e7801-7885-4dee-9061-b7a7c10b3e02.png)

## :sunrise_over_mountains: To Reproduce
1. Unzip the file bellow -> Import the API (change endpoint URL) -> send request using the body in the file.
2. Go to Logs and open the request and in the GW you will see the added comma like in the picture above.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material:

[api.zip](https://github.com/gravitee-io/issues/files/10164735/api.zip)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop 3.18.12
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.18.12

**Comment by gcusnieux** [comment]
The freemarker template use the system Locale.

Two possible solutions
- Add a Locale field in policy configuration
- Get Locale from `Accept-Language` header

**Comment by malick-dev** [comment]
Hello,

we finally found a simpler solution : 

We specify "?c" for each use of an integer type value in the description of policy-assign-content

we set 

`<IdPosteDistribution>${body.IdPosteDistribution?c}</IdPosteDistribution>`

instead of

`<IdPosteDistribution>${body.IdPosteDistribution}</IdPosteDistribution>`

during the transition from the JSON body to XML of the REST request to SOAP, This allows to format the integers in a "computer" format

Thanks for your help @marijatimovska 

Regards,
