### ISSUE TITLE
[portal] Sign new user not working when is enable

### ISSUE THREAD

**Issue by Emmanuel35** [gravitee-io/issues#874]
### Expected Behavior

I would to add new user with UI Management.

### Current Behavior

In default configuration (docker), userCreationEnabled is true for portal.
But When i sign a new user, http://managementui-gravitee.minishift.local/#!/registration, I have a message **The user registration is disabled**

### Steps to Reproduce (for bugs)
1. Install with Docker (me on Openshift)
2. Go to http://managementui-gravitee.minishift.local/#!/registration
3. Add information into form:
- First name
- Last name
- Email
4. Clic on "Sign up"
5. Message: **The user registration is disabled**

### Context

Any change on default configuration.

### Your Environment
* Version used: 1.10.4
* Browser Name and version: Firefox / Chrome
* Operating System and version: OpenShift RedHat / Docker

**Comment by brasseld** [comment]
Hi @Emmanuel35,

I think its due to the fact that user registration is not enabled also for management-api:
https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml#L264

Also, do not forget to set portalURL: https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-management-api-standalone/gravitee-management-api-standalone-distribution/src/main/resources/config/gravitee.yml#L269

To the url of your portal (used for user registration link).

Please let us know.

Regards,

**Comment by brasseld** [comment]
Hi @Emmanuel35 

Any news on this ?

**Comment by Emmanuel35** [comment]
Hi,

Thank for your feedback.
After this modification I have change my docker creation images to include
this file. Email is new sended on signing.

Maybe should you be interested to use my Openshift Docker deployment ??

Emmanuel

2017-11-08 10:40 GMT+01:00 Brassely David <notifications@github.com>:

**Comment by brasseld** [comment]
_Maybe should you be interested to use my Openshift Docker deployment ??_

I would say: YESSSSSS !

**Comment by Emmanuel35** [comment]
I have done a branch openshift-3.6 on gravitee-docker clone.
https://github.com/MiddlewareSolutions/gravitee-docker.git

How to do ?
A Pull Request on gravitee-docker ?
A Pull request on gravitee-openshift ? I can't do that into an empty
projet...

Emmanuel

2017-11-08 12:23 GMT+01:00 Brassely David <notifications@github.com>:

**Comment by brasseld** [comment]
Ok I've initialized the repository with a simple README file.

So you should be able to provide your PR.

Waiting for your feedback.

Regards,

**Comment by brasseld** [comment]
This issue is already fixed
