### ISSUE TITLE
[docker] Externalize gravitee.yml configuration from Dockerfile

### ISSUE THREAD

**Issue by Tony-Proum** [gravitee-io/issues#93]
In order to deploy gravitee using docker, we should use env-file to configure private datas like user/password and other parameters.

we should be able to override all parameters in the same way as ES or Mongo parameters

**Comment by NicolasGeraud** [comment]
Are you ok for variable names like: 
GRAVITEEIO_MONGODB_HOST
GRAVITEEIO_USERS_ADMIN_NAME
GRAVITEEIO_USERS_ADMIN_PWD
?

**Comment by Tony-Proum** [comment]
Yes, I think this names are explicit enough.

**Comment by brasseld** [comment]
Waiting for docker test campaign.

**Comment by kwiky** [comment]
Hi !

Is GRAVITEEIO_USERS_ADMIN_PWD working ?

I'm using your docker image and launch the manager with GRAVITEEIO_USERS_ADMIN_PWD env variable but it's not working, i always have the password "admin" and i can't change it threw the management ui...

**Comment by NicolasGeraud** [comment]
Hi @kwiky , as you can see in https://github.com/gravitee-io/gravitee-management-rest-api/pull/99/files we have only variabilize mongo and elastic configurations.

Because we think that our gravitee images are not "production ready" yet. Nobody use the default configuration in production, specially considering users (all of our customers use LDAP as identity provider).

Is it ok for you ?
